/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePipelineResponse,
  DeletePipelineResponse,
  GetDeepResearchResponse,
  GetPipelineEventsResponse,
  GetPipelineMetricsResponse,
  GetPipelineResponse,
  GetPipelinesResponse,
  GetWorkspaces400Response,
  PipelineConfigurationSchema,
  RetrieveDocumentsRequest,
  RetrieveDocumentsResponse,
  StartDeepResearchRequest,
  StartDeepResearchResponse,
  StartPipelineResponse,
  StopPipelineResponse,
} from '../models/index';
import {
    CreatePipelineResponseFromJSON,
    CreatePipelineResponseToJSON,
    DeletePipelineResponseFromJSON,
    DeletePipelineResponseToJSON,
    GetDeepResearchResponseFromJSON,
    GetDeepResearchResponseToJSON,
    GetPipelineEventsResponseFromJSON,
    GetPipelineEventsResponseToJSON,
    GetPipelineMetricsResponseFromJSON,
    GetPipelineMetricsResponseToJSON,
    GetPipelineResponseFromJSON,
    GetPipelineResponseToJSON,
    GetPipelinesResponseFromJSON,
    GetPipelinesResponseToJSON,
    GetWorkspaces400ResponseFromJSON,
    GetWorkspaces400ResponseToJSON,
    PipelineConfigurationSchemaFromJSON,
    PipelineConfigurationSchemaToJSON,
    RetrieveDocumentsRequestFromJSON,
    RetrieveDocumentsRequestToJSON,
    RetrieveDocumentsResponseFromJSON,
    RetrieveDocumentsResponseToJSON,
    StartDeepResearchRequestFromJSON,
    StartDeepResearchRequestToJSON,
    StartDeepResearchResponseFromJSON,
    StartDeepResearchResponseToJSON,
    StartPipelineResponseFromJSON,
    StartPipelineResponseToJSON,
    StopPipelineResponseFromJSON,
    StopPipelineResponseToJSON,
} from '../models/index';

export interface CreatePipelineRequest {
    organizationId: string;
    pipelineConfigurationSchema: PipelineConfigurationSchema;
    workspaceId?: string;
}

export interface DeletePipelineRequest {
    organizationId: string;
    pipelineId: string;
}

export interface GetDeepResearchResultRequest {
    organizationId: string;
    pipelineId: string;
    researchId: string;
}

export interface GetPipelineRequest {
    organizationId: string;
    pipelineId: string;
}

export interface GetPipelineEventsRequest {
    organizationId: string;
    pipelineId: string;
    nextToken?: string;
}

export interface GetPipelineMetricsRequest {
    organizationId: string;
    pipelineId: string;
}

export interface GetPipelinesRequest {
    organizationId: string;
    workspaceId?: string;
}

export interface RetrieveDocumentsOperationRequest {
    organizationId: string;
    pipelineId: string;
    retrieveDocumentsRequest: RetrieveDocumentsRequest;
}

export interface StartDeepResearchOperationRequest {
    organizationId: string;
    pipelineId: string;
    startDeepResearchRequest: StartDeepResearchRequest;
}

export interface StartPipelineRequest {
    organizationId: string;
    pipelineId: string;
}

export interface StopPipelineRequest {
    organizationId: string;
    pipelineId: string;
}

/**
 * 
 */
export class PipelinesApi extends runtime.BaseAPI {

    /**
     * Creates a new pipeline with source connectors, destination connector, and AI platform configuration. The specific configuration fields required depend on the connector types selected.
     * Create a new pipeline
     */
    async createPipelineRaw(requestParameters: CreatePipelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePipelineResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling createPipeline().'
            );
        }

        if (requestParameters['pipelineConfigurationSchema'] == null) {
            throw new runtime.RequiredError(
                'pipelineConfigurationSchema',
                'Required parameter "pipelineConfigurationSchema" was null or undefined when calling createPipeline().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspaceId'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PipelineConfigurationSchemaToJSON(requestParameters['pipelineConfigurationSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePipelineResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new pipeline with source connectors, destination connector, and AI platform configuration. The specific configuration fields required depend on the connector types selected.
     * Create a new pipeline
     */
    async createPipeline(requestParameters: CreatePipelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePipelineResponse> {
        const response = await this.createPipelineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a pipeline
     * Delete a pipeline
     */
    async deletePipelineRaw(requestParameters: DeletePipelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeletePipelineResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling deletePipeline().'
            );
        }

        if (requestParameters['pipelineId'] == null) {
            throw new runtime.RequiredError(
                'pipelineId',
                'Required parameter "pipelineId" was null or undefined when calling deletePipeline().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines/{pipelineId}`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters['pipelineId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeletePipelineResponseFromJSON(jsonValue));
    }

    /**
     * Delete a pipeline
     * Delete a pipeline
     */
    async deletePipeline(requestParameters: DeletePipelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeletePipelineResponse> {
        const response = await this.deletePipelineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get deep research result
     * Get deep research result
     */
    async getDeepResearchResultRaw(requestParameters: GetDeepResearchResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDeepResearchResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling getDeepResearchResult().'
            );
        }

        if (requestParameters['pipelineId'] == null) {
            throw new runtime.RequiredError(
                'pipelineId',
                'Required parameter "pipelineId" was null or undefined when calling getDeepResearchResult().'
            );
        }

        if (requestParameters['researchId'] == null) {
            throw new runtime.RequiredError(
                'researchId',
                'Required parameter "researchId" was null or undefined when calling getDeepResearchResult().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines/{pipelineId}/deep-research/{researchId}`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters['pipelineId']))).replace(`{${"researchId"}}`, encodeURIComponent(String(requestParameters['researchId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDeepResearchResponseFromJSON(jsonValue));
    }

    /**
     * Get deep research result
     * Get deep research result
     */
    async getDeepResearchResult(requestParameters: GetDeepResearchResultRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDeepResearchResponse> {
        const response = await this.getDeepResearchResultRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a pipeline
     * Get a pipeline
     */
    async getPipelineRaw(requestParameters: GetPipelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPipelineResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling getPipeline().'
            );
        }

        if (requestParameters['pipelineId'] == null) {
            throw new runtime.RequiredError(
                'pipelineId',
                'Required parameter "pipelineId" was null or undefined when calling getPipeline().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines/{pipelineId}`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters['pipelineId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPipelineResponseFromJSON(jsonValue));
    }

    /**
     * Get a pipeline
     * Get a pipeline
     */
    async getPipeline(requestParameters: GetPipelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPipelineResponse> {
        const response = await this.getPipelineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get pipeline events
     * Get pipeline events
     */
    async getPipelineEventsRaw(requestParameters: GetPipelineEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPipelineEventsResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling getPipelineEvents().'
            );
        }

        if (requestParameters['pipelineId'] == null) {
            throw new runtime.RequiredError(
                'pipelineId',
                'Required parameter "pipelineId" was null or undefined when calling getPipelineEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['nextToken'] != null) {
            queryParameters['nextToken'] = requestParameters['nextToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines/{pipelineId}/events`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters['pipelineId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPipelineEventsResponseFromJSON(jsonValue));
    }

    /**
     * Get pipeline events
     * Get pipeline events
     */
    async getPipelineEvents(requestParameters: GetPipelineEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPipelineEventsResponse> {
        const response = await this.getPipelineEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get pipeline metrics
     * Get pipeline metrics
     */
    async getPipelineMetricsRaw(requestParameters: GetPipelineMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPipelineMetricsResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling getPipelineMetrics().'
            );
        }

        if (requestParameters['pipelineId'] == null) {
            throw new runtime.RequiredError(
                'pipelineId',
                'Required parameter "pipelineId" was null or undefined when calling getPipelineMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines/{pipelineId}/metrics`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters['pipelineId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPipelineMetricsResponseFromJSON(jsonValue));
    }

    /**
     * Get pipeline metrics
     * Get pipeline metrics
     */
    async getPipelineMetrics(requestParameters: GetPipelineMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPipelineMetricsResponse> {
        const response = await this.getPipelineMetricsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a list of all pipelines in the organization
     * Get all pipelines
     */
    async getPipelinesRaw(requestParameters: GetPipelinesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetPipelinesResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling getPipelines().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['workspaceId'] != null) {
            queryParameters['workspaceId'] = requestParameters['workspaceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPipelinesResponseFromJSON(jsonValue));
    }

    /**
     * Returns a list of all pipelines in the organization
     * Get all pipelines
     */
    async getPipelines(requestParameters: GetPipelinesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetPipelinesResponse> {
        const response = await this.getPipelinesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve documents from a pipeline
     * Retrieve documents from a pipeline
     */
    async retrieveDocumentsRaw(requestParameters: RetrieveDocumentsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RetrieveDocumentsResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling retrieveDocuments().'
            );
        }

        if (requestParameters['pipelineId'] == null) {
            throw new runtime.RequiredError(
                'pipelineId',
                'Required parameter "pipelineId" was null or undefined when calling retrieveDocuments().'
            );
        }

        if (requestParameters['retrieveDocumentsRequest'] == null) {
            throw new runtime.RequiredError(
                'retrieveDocumentsRequest',
                'Required parameter "retrieveDocumentsRequest" was null or undefined when calling retrieveDocuments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines/{pipelineId}/retrieval`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters['pipelineId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RetrieveDocumentsRequestToJSON(requestParameters['retrieveDocumentsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RetrieveDocumentsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve documents from a pipeline
     * Retrieve documents from a pipeline
     */
    async retrieveDocuments(requestParameters: RetrieveDocumentsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RetrieveDocumentsResponse> {
        const response = await this.retrieveDocumentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a deep research
     * Start a deep research
     */
    async startDeepResearchRaw(requestParameters: StartDeepResearchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartDeepResearchResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling startDeepResearch().'
            );
        }

        if (requestParameters['pipelineId'] == null) {
            throw new runtime.RequiredError(
                'pipelineId',
                'Required parameter "pipelineId" was null or undefined when calling startDeepResearch().'
            );
        }

        if (requestParameters['startDeepResearchRequest'] == null) {
            throw new runtime.RequiredError(
                'startDeepResearchRequest',
                'Required parameter "startDeepResearchRequest" was null or undefined when calling startDeepResearch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines/{pipelineId}/deep-research`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters['pipelineId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartDeepResearchRequestToJSON(requestParameters['startDeepResearchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartDeepResearchResponseFromJSON(jsonValue));
    }

    /**
     * Start a deep research
     * Start a deep research
     */
    async startDeepResearch(requestParameters: StartDeepResearchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartDeepResearchResponse> {
        const response = await this.startDeepResearchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a pipeline
     * Start a pipeline
     */
    async startPipelineRaw(requestParameters: StartPipelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StartPipelineResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling startPipeline().'
            );
        }

        if (requestParameters['pipelineId'] == null) {
            throw new runtime.RequiredError(
                'pipelineId',
                'Required parameter "pipelineId" was null or undefined when calling startPipeline().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines/{pipelineId}/start`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters['pipelineId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StartPipelineResponseFromJSON(jsonValue));
    }

    /**
     * Start a pipeline
     * Start a pipeline
     */
    async startPipeline(requestParameters: StartPipelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StartPipelineResponse> {
        const response = await this.startPipelineRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Stop a pipeline
     * Stop a pipeline
     */
    async stopPipelineRaw(requestParameters: StopPipelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StopPipelineResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling stopPipeline().'
            );
        }

        if (requestParameters['pipelineId'] == null) {
            throw new runtime.RequiredError(
                'pipelineId',
                'Required parameter "pipelineId" was null or undefined when calling stopPipeline().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/org/{organizationId}/pipelines/{pipelineId}/stop`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters['pipelineId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StopPipelineResponseFromJSON(jsonValue));
    }

    /**
     * Stop a pipeline
     * Stop a pipeline
     */
    async stopPipeline(requestParameters: StopPipelineRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StopPipelineResponse> {
        const response = await this.stopPipelineRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
