# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.google_drive_oauth_multi_custom2 import GoogleDriveOauthMultiCustom2

class TestGoogleDriveOauthMultiCustom2(unittest.TestCase):
    """GoogleDriveOauthMultiCustom2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoogleDriveOauthMultiCustom2:
        """Test GoogleDriveOauthMultiCustom2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoogleDriveOauthMultiCustom2`
        """
        model = GoogleDriveOauthMultiCustom2()
        if include_optional:
            return GoogleDriveOauthMultiCustom2(
                id = '',
                type = 'GOOGLE_DRIVE_OAUTH_MULTI_CUSTOM'
            )
        else:
            return GoogleDriveOauthMultiCustom2(
                id = '',
                type = 'GOOGLE_DRIVE_OAUTH_MULTI_CUSTOM',
        )
        """

    def testGoogleDriveOauthMultiCustom2(self):
        """Test GoogleDriveOauthMultiCustom2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
