# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.vertex1 import Vertex1

class TestVertex1(unittest.TestCase):
    """Vertex1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Vertex1:
        """Test Vertex1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Vertex1`
        """
        model = Vertex1()
        if include_optional:
            return Vertex1(
                config = vectorize_client.models.vertex_auth_config.VERTEXAuthConfig(
                    name = '', 
                    key = '', 
                    region = '', )
            )
        else:
            return Vertex1(
        )
        """

    def testVertex1(self):
        """Test Vertex1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
