# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.api.connectors_destination_connectors_api import ConnectorsDestinationConnectorsApi


class TestConnectorsDestinationConnectorsApi(unittest.TestCase):
    """ConnectorsDestinationConnectorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsDestinationConnectorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_destination_connector(self) -> None:
        """Test case for create_destination_connector

        Create a new destination connector
        """
        pass

    def test_delete_destination_connector(self) -> None:
        """Test case for delete_destination_connector

        Delete a destination connector
        """
        pass

    def test_get_destination_connector(self) -> None:
        """Test case for get_destination_connector

        Get a destination connector
        """
        pass

    def test_get_destination_connectors(self) -> None:
        """Test case for get_destination_connectors

        Get all existing destination connectors
        """
        pass

    def test_update_destination_connector(self) -> None:
        """Test case for update_destination_connector

        Update a destination connector
        """
        pass


if __name__ == '__main__':
    unittest.main()
