# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.advanced_query import AdvancedQuery

class TestAdvancedQuery(unittest.TestCase):
    """AdvancedQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvancedQuery:
        """Test AdvancedQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvancedQuery`
        """
        model = AdvancedQuery()
        if include_optional:
            return AdvancedQuery(
                mode = 'vector',
                text_fields = [
                    ''
                    ],
                match_type = 'match',
                text_boost = 1.337,
                filters = { }
            )
        else:
            return AdvancedQuery(
        )
        """

    def testAdvancedQuery(self):
        """Test AdvancedQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
