# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.start_file_upload_response import StartFileUploadResponse

class TestStartFileUploadResponse(unittest.TestCase):
    """StartFileUploadResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartFileUploadResponse:
        """Test StartFileUploadResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartFileUploadResponse`
        """
        model = StartFileUploadResponse()
        if include_optional:
            return StartFileUploadResponse(
                file_id = '',
                upload_url = ''
            )
        else:
            return StartFileUploadResponse(
                file_id = '',
                upload_url = '',
        )
        """

    def testStartFileUploadResponse(self):
        """Test StartFileUploadResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
