# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.notion2 import Notion2

class TestNotion2(unittest.TestCase):
    """Notion2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Notion2:
        """Test Notion2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Notion2`
        """
        model = Notion2()
        if include_optional:
            return Notion2(
                id = '',
                type = 'NOTION'
            )
        else:
            return Notion2(
                id = '',
                type = 'NOTION',
        )
        """

    def testNotion2(self):
        """Test Notion2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
