# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.elastic import Elastic

class TestElastic(unittest.TestCase):
    """Elastic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Elastic:
        """Test Elastic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Elastic`
        """
        model = Elastic()
        if include_optional:
            return Elastic(
                name = '',
                type = 'ELASTIC',
                config = ERROR_TO_EXAMPLE_VALUE
            )
        else:
            return Elastic(
                name = '',
                type = 'ELASTIC',
                config = ERROR_TO_EXAMPLE_VALUE,
        )
        """

    def testElastic(self):
        """Test Elastic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
