# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.created_destination_connector import CreatedDestinationConnector

class TestCreatedDestinationConnector(unittest.TestCase):
    """CreatedDestinationConnector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatedDestinationConnector:
        """Test CreatedDestinationConnector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatedDestinationConnector`
        """
        model = CreatedDestinationConnector()
        if include_optional:
            return CreatedDestinationConnector(
                name = '',
                id = ''
            )
        else:
            return CreatedDestinationConnector(
                name = '',
                id = '',
        )
        """

    def testCreatedDestinationConnector(self):
        """Test CreatedDestinationConnector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
