# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.one_drive2 import OneDrive2

class TestOneDrive2(unittest.TestCase):
    """OneDrive2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OneDrive2:
        """Test OneDrive2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OneDrive2`
        """
        model = OneDrive2()
        if include_optional:
            return OneDrive2(
                id = '',
                type = 'ONE_DRIVE'
            )
        else:
            return OneDrive2(
                id = '',
                type = 'ONE_DRIVE',
        )
        """

    def testOneDrive2(self):
        """Test OneDrive2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
