# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.pipeline_destination_connector_request_inner import PipelineDestinationConnectorRequestInner

class TestPipelineDestinationConnectorRequestInner(unittest.TestCase):
    """PipelineDestinationConnectorRequestInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PipelineDestinationConnectorRequestInner:
        """Test PipelineDestinationConnectorRequestInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PipelineDestinationConnectorRequestInner`
        """
        model = PipelineDestinationConnectorRequestInner()
        if include_optional:
            return PipelineDestinationConnectorRequestInner(
                id = '',
                type = 'CAPELLA'
            )
        else:
            return PipelineDestinationConnectorRequestInner(
                id = '',
                type = 'CAPELLA',
        )
        """

    def testPipelineDestinationConnectorRequestInner(self):
        """Test PipelineDestinationConnectorRequestInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
