# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.api.connectors_source_connectors_api import ConnectorsSourceConnectorsApi


class TestConnectorsSourceConnectorsApi(unittest.TestCase):
    """ConnectorsSourceConnectorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsSourceConnectorsApi()

    def tearDown(self) -> None:
        pass

    def test_add_user_to_source_connector(self) -> None:
        """Test case for add_user_to_source_connector

        Add a user to a source connector
        """
        pass

    def test_create_source_connector(self) -> None:
        """Test case for create_source_connector

        Create a new source connector
        """
        pass

    def test_delete_source_connector(self) -> None:
        """Test case for delete_source_connector

        Delete a source connector
        """
        pass

    def test_delete_user_from_source_connector(self) -> None:
        """Test case for delete_user_from_source_connector

        Delete a source connector user
        """
        pass

    def test_get_source_connector(self) -> None:
        """Test case for get_source_connector

        Get a source connector
        """
        pass

    def test_get_source_connectors(self) -> None:
        """Test case for get_source_connectors

        Get all existing source connectors
        """
        pass

    def test_update_source_connector(self) -> None:
        """Test case for update_source_connector

        Update a source connector
        """
        pass

    def test_update_user_in_source_connector(self) -> None:
        """Test case for update_user_in_source_connector

        Update a source connector user
        """
        pass


if __name__ == '__main__':
    unittest.main()
