# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.start_file_upload_to_connector_response import StartFileUploadToConnectorResponse

class TestStartFileUploadToConnectorResponse(unittest.TestCase):
    """StartFileUploadToConnectorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartFileUploadToConnectorResponse:
        """Test StartFileUploadToConnectorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartFileUploadToConnectorResponse`
        """
        model = StartFileUploadToConnectorResponse()
        if include_optional:
            return StartFileUploadToConnectorResponse(
                upload_url = ''
            )
        else:
            return StartFileUploadToConnectorResponse(
                upload_url = '',
        )
        """

    def testStartFileUploadToConnectorResponse(self):
        """Test StartFileUploadToConnectorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
