# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.sharepoint_auth_config import SHAREPOINTAuthConfig

class TestSHAREPOINTAuthConfig(unittest.TestCase):
    """SHAREPOINTAuthConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SHAREPOINTAuthConfig:
        """Test SHAREPOINTAuthConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SHAREPOINTAuthConfig`
        """
        model = SHAREPOINTAuthConfig()
        if include_optional:
            return SHAREPOINTAuthConfig(
                name = '',
                ms_client_id = '',
                ms_tenant_id = '',
                ms_client_secret = ''
            )
        else:
            return SHAREPOINTAuthConfig(
                name = '',
                ms_client_id = '',
                ms_tenant_id = '',
                ms_client_secret = '',
        )
        """

    def testSHAREPOINTAuthConfig(self):
        """Test SHAREPOINTAuthConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
