# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.pipeline_configuration_schema import PipelineConfigurationSchema

class TestPipelineConfigurationSchema(unittest.TestCase):
    """PipelineConfigurationSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PipelineConfigurationSchema:
        """Test PipelineConfigurationSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PipelineConfigurationSchema`
        """
        model = PipelineConfigurationSchema()
        if include_optional:
            return PipelineConfigurationSchema(
                source_connectors = [
                    vectorize_client.models.source_connector_schema.SourceConnectorSchema(
                        id = '', 
                        type = 'AWS_S3', 
                        config = {
                            'key' : null
                            }, )
                    ],
                destination_connector = vectorize_client.models.destination_connector_schema.DestinationConnectorSchema(
                    id = '', 
                    type = 'CAPELLA', 
                    config = {
                        'key' : null
                        }, ),
                ai_platform = vectorize_client.models.ai_platform_schema.AIPlatformSchema(
                    id = '', 
                    type = 'BEDROCK', 
                    config = vectorize_client.models.ai_platform_config_schema.AIPlatformConfigSchema(
                        embedding_model = 'VECTORIZE_OPEN_AI_TEXT_EMBEDDING_2', 
                        chunking_strategy = 'FIXED', 
                        chunk_size = 1, 
                        chunk_overlap = 0, 
                        dimensions = 1, 
                        extraction_strategy = 'FAST', ), ),
                pipeline_name = '0',
                schedule = vectorize_client.models.schedule_schema.ScheduleSchema(
                    type = 'manual', )
            )
        else:
            return PipelineConfigurationSchema(
                source_connectors = [
                    vectorize_client.models.source_connector_schema.SourceConnectorSchema(
                        id = '', 
                        type = 'AWS_S3', 
                        config = {
                            'key' : null
                            }, )
                    ],
                destination_connector = vectorize_client.models.destination_connector_schema.DestinationConnectorSchema(
                    id = '', 
                    type = 'CAPELLA', 
                    config = {
                        'key' : null
                        }, ),
                ai_platform = vectorize_client.models.ai_platform_schema.AIPlatformSchema(
                    id = '', 
                    type = 'BEDROCK', 
                    config = vectorize_client.models.ai_platform_config_schema.AIPlatformConfigSchema(
                        embedding_model = 'VECTORIZE_OPEN_AI_TEXT_EMBEDDING_2', 
                        chunking_strategy = 'FIXED', 
                        chunk_size = 1, 
                        chunk_overlap = 0, 
                        dimensions = 1, 
                        extraction_strategy = 'FAST', ), ),
                pipeline_name = '0',
                schedule = vectorize_client.models.schedule_schema.ScheduleSchema(
                    type = 'manual', ),
        )
        """

    def testPipelineConfigurationSchema(self):
        """Test PipelineConfigurationSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
