# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.one_drive import OneDrive

class TestOneDrive(unittest.TestCase):
    """OneDrive unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OneDrive:
        """Test OneDrive
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OneDrive`
        """
        model = OneDrive()
        if include_optional:
            return OneDrive(
                name = '',
                type = 'ONE_DRIVE',
                config = vectorize_client.models.one_drive_config.ONE_DRIVEConfig(
                    file_extensions = pdf, 
                    path_prefix = '', )
            )
        else:
            return OneDrive(
                name = '',
                type = 'ONE_DRIVE',
                config = vectorize_client.models.one_drive_config.ONE_DRIVEConfig(
                    file_extensions = pdf, 
                    path_prefix = '', ),
        )
        """

    def testOneDrive(self):
        """Test OneDrive"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
