# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.intercom import Intercom

class TestIntercom(unittest.TestCase):
    """Intercom unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Intercom:
        """Test Intercom
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Intercom`
        """
        model = Intercom()
        if include_optional:
            return Intercom(
                name = '',
                type = 'INTERCOM',
                config = vectorize_client.models.intercom_config.INTERCOMConfig(
                    created_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    updated_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    state = open, )
            )
        else:
            return Intercom(
                name = '',
                type = 'INTERCOM',
                config = vectorize_client.models.intercom_config.INTERCOMConfig(
                    created_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    updated_at = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    state = open, ),
        )
        """

    def testIntercom(self):
        """Test Intercom"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
