# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.update_destination_connector_response import UpdateDestinationConnectorResponse

class TestUpdateDestinationConnectorResponse(unittest.TestCase):
    """UpdateDestinationConnectorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateDestinationConnectorResponse:
        """Test UpdateDestinationConnectorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateDestinationConnectorResponse`
        """
        model = UpdateDestinationConnectorResponse()
        if include_optional:
            return UpdateDestinationConnectorResponse(
                message = '',
                data = vectorize_client.models.updated_destination_connector_data.UpdatedDestinationConnectorData(
                    updated_connector = vectorize_client.models.destination_connector.DestinationConnector(
                        id = '', 
                        type = '', 
                        name = '', 
                        config_doc = {
                            'key' : null
                            }, 
                        created_at = '', 
                        created_by_id = '', 
                        last_updated_by_id = '', 
                        created_by_email = '', 
                        last_updated_by_email = '', 
                        error_message = '', 
                        verification_status = '', ), 
                    pipeline_ids = [
                        ''
                        ], )
            )
        else:
            return UpdateDestinationConnectorResponse(
                message = '',
                data = vectorize_client.models.updated_destination_connector_data.UpdatedDestinationConnectorData(
                    updated_connector = vectorize_client.models.destination_connector.DestinationConnector(
                        id = '', 
                        type = '', 
                        name = '', 
                        config_doc = {
                            'key' : null
                            }, 
                        created_at = '', 
                        created_by_id = '', 
                        last_updated_by_id = '', 
                        created_by_email = '', 
                        last_updated_by_email = '', 
                        error_message = '', 
                        verification_status = '', ), 
                    pipeline_ids = [
                        ''
                        ], ),
        )
        """

    def testUpdateDestinationConnectorResponse(self):
        """Test UpdateDestinationConnectorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
