# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.file_upload1 import FileUpload1

class TestFileUpload1(unittest.TestCase):
    """FileUpload1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileUpload1:
        """Test FileUpload1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileUpload1`
        """
        model = FileUpload1()
        if include_optional:
            return FileUpload1(
                config = vectorize_client.models.file_upload_auth_config.FILE_UPLOADAuthConfig(
                    name = '', 
                    path_prefix = '', 
                    files = [
                        ''
                        ], )
            )
        else:
            return FileUpload1(
        )
        """

    def testFileUpload1(self):
        """Test FileUpload1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
