# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.capella2 import Capella2

class TestCapella2(unittest.TestCase):
    """Capella2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Capella2:
        """Test Capella2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Capella2`
        """
        model = Capella2()
        if include_optional:
            return Capella2(
                id = '',
                type = 'CAPELLA'
            )
        else:
            return Capella2(
                id = '',
                type = 'CAPELLA',
        )
        """

    def testCapella2(self):
        """Test Capella2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
