# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.get_source_connectors200_response import GetSourceConnectors200Response

class TestGetSourceConnectors200Response(unittest.TestCase):
    """GetSourceConnectors200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSourceConnectors200Response:
        """Test GetSourceConnectors200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSourceConnectors200Response`
        """
        model = GetSourceConnectors200Response()
        if include_optional:
            return GetSourceConnectors200Response(
                source_connectors = [
                    vectorize_client.models.source_connector.SourceConnector(
                        id = '', 
                        type = '', 
                        name = '', 
                        config_doc = {
                            'key' : null
                            }, 
                        created_at = '', 
                        created_by_id = '', 
                        last_updated_by_id = '', 
                        created_by_email = '', 
                        last_updated_by_email = '', 
                        error_message = '', 
                        verification_status = '', )
                    ]
            )
        else:
            return GetSourceConnectors200Response(
                source_connectors = [
                    vectorize_client.models.source_connector.SourceConnector(
                        id = '', 
                        type = '', 
                        name = '', 
                        config_doc = {
                            'key' : null
                            }, 
                        created_at = '', 
                        created_by_id = '', 
                        last_updated_by_id = '', 
                        created_by_email = '', 
                        last_updated_by_email = '', 
                        error_message = '', 
                        verification_status = '', )
                    ],
        )
        """

    def testGetSourceConnectors200Response(self):
        """Test GetSourceConnectors200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
