# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.dropbox_oauth_multi_custom import DropboxOauthMultiCustom

class TestDropboxOauthMultiCustom(unittest.TestCase):
    """DropboxOauthMultiCustom unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DropboxOauthMultiCustom:
        """Test DropboxOauthMultiCustom
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DropboxOauthMultiCustom`
        """
        model = DropboxOauthMultiCustom()
        if include_optional:
            return DropboxOauthMultiCustom(
                name = '',
                type = 'DROPBOX_OAUTH_MULTI_CUSTOM',
                config = vectorize_client.models.dropbox_oauth_multi_custom_auth_config.DROPBOX_OAUTH_MULTI_CUSTOMAuthConfig(
                    name = '', 
                    app_key = '', 
                    app_secret = '', 
                    authorized_users = '', 
                    edited_users = '', 
                    deleted_users = '', )
            )
        else:
            return DropboxOauthMultiCustom(
                name = '',
                type = 'DROPBOX_OAUTH_MULTI_CUSTOM',
                config = vectorize_client.models.dropbox_oauth_multi_custom_auth_config.DROPBOX_OAUTH_MULTI_CUSTOMAuthConfig(
                    name = '', 
                    app_key = '', 
                    app_secret = '', 
                    authorized_users = '', 
                    edited_users = '', 
                    deleted_users = '', ),
        )
        """

    def testDropboxOauthMultiCustom(self):
        """Test DropboxOauthMultiCustom"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
