# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.amazon_s31 import AmazonS31

class TestAmazonS31(unittest.TestCase):
    """AmazonS31 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AmazonS31:
        """Test AmazonS31
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AmazonS31`
        """
        model = AmazonS31()
        if include_optional:
            return AmazonS31(
                config = vectorize_client.models.aws_s3_config.AWS_S3Config(
                    file_extensions = pdf, 
                    idle_time = 1, 
                    recursive = True, 
                    path_prefix = '', 
                    path_metadata_regex = '', 
                    path_regex_group_names = '', )
            )
        else:
            return AmazonS31(
        )
        """

    def testAmazonS31(self):
        """Test AmazonS31"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
