# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.sharepoint1 import Sharepoint1

class TestSharepoint1(unittest.TestCase):
    """Sharepoint1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Sharepoint1:
        """Test Sharepoint1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Sharepoint1`
        """
        model = Sharepoint1()
        if include_optional:
            return Sharepoint1(
                config = vectorize_client.models.sharepoint_config.SHAREPOINTConfig(
                    file_extensions = pdf, 
                    sites = 'UR,r8NBY08qY UboV 2Ow7qrz 0IL3 fR', )
            )
        else:
            return Sharepoint1(
        )
        """

    def testSharepoint1(self):
        """Test Sharepoint1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
