# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.dropbox1 import Dropbox1

class TestDropbox1(unittest.TestCase):
    """Dropbox1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dropbox1:
        """Test Dropbox1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dropbox1`
        """
        model = Dropbox1()
        if include_optional:
            return Dropbox1(
                config = vectorize_client.models.dropbox_config.DROPBOXConfig(
                    path_prefix = '/jUR,rZ#UM/?R,Fp^l6$ARj', )
            )
        else:
            return Dropbox1(
        )
        """

    def testDropbox1(self):
        """Test Dropbox1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
