# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.firecrawl1 import Firecrawl1

class TestFirecrawl1(unittest.TestCase):
    """Firecrawl1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Firecrawl1:
        """Test Firecrawl1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Firecrawl1`
        """
        model = Firecrawl1()
        if include_optional:
            return Firecrawl1(
                config = vectorize_client.models.firecrawl_config.FIRECRAWLConfig(
                    endpoint = 'Crawl', 
                    request = vectorize_client.models.request.request(), )
            )
        else:
            return Firecrawl1(
        )
        """

    def testFirecrawl1(self):
        """Test Firecrawl1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
