# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.azureaisearch_config import AZUREAISEARCHConfig

class TestAZUREAISEARCHConfig(unittest.TestCase):
    """AZUREAISEARCHConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AZUREAISEARCHConfig:
        """Test AZUREAISEARCHConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AZUREAISEARCHConfig`
        """
        model = AZUREAISEARCHConfig()
        if include_optional:
            return AZUREAISEARCHConfig(
                index = 'wr1c2v7s6djuy1zmetozkhdomha1b0'
            )
        else:
            return AZUREAISEARCHConfig(
                index = 'wr1c2v7s6djuy1zmetozkhdomha1b0',
        )
        """

    def testAZUREAISEARCHConfig(self):
        """Test AZUREAISEARCHConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
