# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.azureblob_config import AZUREBLOBConfig

class TestAZUREBLOBConfig(unittest.TestCase):
    """AZUREBLOBConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AZUREBLOBConfig:
        """Test AZUREBLOBConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AZUREBLOBConfig`
        """
        model = AZUREBLOBConfig()
        if include_optional:
            return AZUREBLOBConfig(
                file_extensions = pdf,
                idle_time = 1,
                recursive = True,
                path_prefix = '',
                path_metadata_regex = '',
                path_regex_group_names = ''
            )
        else:
            return AZUREBLOBConfig(
                file_extensions = pdf,
                idle_time = 1,
        )
        """

    def testAZUREBLOBConfig(self):
        """Test AZUREBLOBConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
