# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.pipeline_ai_platform_request_inner import PipelineAIPlatformRequestInner

class TestPipelineAIPlatformRequestInner(unittest.TestCase):
    """PipelineAIPlatformRequestInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PipelineAIPlatformRequestInner:
        """Test PipelineAIPlatformRequestInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PipelineAIPlatformRequestInner`
        """
        model = PipelineAIPlatformRequestInner()
        if include_optional:
            return PipelineAIPlatformRequestInner(
                id = '',
                type = 'BEDROCK'
            )
        else:
            return PipelineAIPlatformRequestInner(
                id = '',
                type = 'BEDROCK',
        )
        """

    def testPipelineAIPlatformRequestInner(self):
        """Test PipelineAIPlatformRequestInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
