# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.confluence1 import Confluence1

class TestConfluence1(unittest.TestCase):
    """Confluence1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Confluence1:
        """Test Confluence1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Confluence1`
        """
        model = Confluence1()
        if include_optional:
            return Confluence1(
                config = vectorize_client.models.confluence_config.CONFLUENCEConfig(
                    spaces = '', 
                    root_parents = '', )
            )
        else:
            return Confluence1(
        )
        """

    def testConfluence1(self):
        """Test Confluence1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
