# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.dropbox_oauth2 import DropboxOauth2

class TestDropboxOauth2(unittest.TestCase):
    """DropboxOauth2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DropboxOauth2:
        """Test DropboxOauth2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DropboxOauth2`
        """
        model = DropboxOauth2()
        if include_optional:
            return DropboxOauth2(
                id = '',
                type = 'DROPBOX_OAUTH'
            )
        else:
            return DropboxOauth2(
                id = '',
                type = 'DROPBOX_OAUTH',
        )
        """

    def testDropboxOauth2(self):
        """Test DropboxOauth2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
