# coding: utf-8

"""
    Vectorize API (Beta)

    API for Vectorize services

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vectorize_client.models.dropbox_oauth1 import DropboxOauth1

class TestDropboxOauth1(unittest.TestCase):
    """DropboxOauth1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DropboxOauth1:
        """Test DropboxOauth1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DropboxOauth1`
        """
        model = DropboxOauth1()
        if include_optional:
            return DropboxOauth1(
                config = vectorize_client.models.dropbox_oauth_auth_config.DROPBOX_OAUTHAuthConfig(
                    name = '', 
                    authorized_user = '', 
                    selection_details = '', 
                    edited_users = '', 
                    reconnect_users = '', )
            )
        else:
            return DropboxOauth1(
        )
        """

    def testDropboxOauth1(self):
        """Test DropboxOauth1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
