/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddUserToSourceConnectorRequestSelectedFilesAnyOfValue
 */
export interface AddUserToSourceConnectorRequestSelectedFilesAnyOfValue {
    /**
     * 
     * @type {string}
     * @memberof AddUserToSourceConnectorRequestSelectedFilesAnyOfValue
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AddUserToSourceConnectorRequestSelectedFilesAnyOfValue
     */
    mimeType: string;
}

/**
 * Check if a given object implements the AddUserToSourceConnectorRequestSelectedFilesAnyOfValue interface.
 */
export function instanceOfAddUserToSourceConnectorRequestSelectedFilesAnyOfValue(value: object): value is AddUserToSourceConnectorRequestSelectedFilesAnyOfValue {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('mimeType' in value) || value['mimeType'] === undefined) return false;
    return true;
}

export function AddUserToSourceConnectorRequestSelectedFilesAnyOfValueFromJSON(json: any): AddUserToSourceConnectorRequestSelectedFilesAnyOfValue {
    return AddUserToSourceConnectorRequestSelectedFilesAnyOfValueFromJSONTyped(json, false);
}

export function AddUserToSourceConnectorRequestSelectedFilesAnyOfValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserToSourceConnectorRequestSelectedFilesAnyOfValue {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'mimeType': json['mimeType'],
    };
}

export function AddUserToSourceConnectorRequestSelectedFilesAnyOfValueToJSON(json: any): AddUserToSourceConnectorRequestSelectedFilesAnyOfValue {
    return AddUserToSourceConnectorRequestSelectedFilesAnyOfValueToJSONTyped(json, false);
}

export function AddUserToSourceConnectorRequestSelectedFilesAnyOfValueToJSONTyped(value?: AddUserToSourceConnectorRequestSelectedFilesAnyOfValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'mimeType': value['mimeType'],
    };
}

