/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API (Beta)
 * API documentation for Vectorize services
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AIPlatformSchema
 */
export interface AIPlatformSchema {
    /**
     * 
     * @type {string}
     * @memberof AIPlatformSchema
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AIPlatformSchema
     */
    type: string;
    /**
     * 
     * @type {object}
     * @memberof AIPlatformSchema
     */
    config: object;
}

/**
 * Check if a given object implements the AIPlatformSchema interface.
 */
export function instanceOfAIPlatformSchema(value: object): value is AIPlatformSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function AIPlatformSchemaFromJSON(json: any): AIPlatformSchema {
    return AIPlatformSchemaFromJSONTyped(json, false);
}

export function AIPlatformSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AIPlatformSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'config': json['config'],
    };
}

export function AIPlatformSchemaToJSON(json: any): AIPlatformSchema {
    return AIPlatformSchemaToJSONTyped(json, false);
}

export function AIPlatformSchemaToJSONTyped(value?: AIPlatformSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'config': value['config'],
    };
}

