/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AIPlatformType = {
    Bedrock: 'BEDROCK',
    Vertex: 'VERTEX',
    Openai: 'OPENAI',
    Voyage: 'VOYAGE'
} as const;
export type AIPlatformType = typeof AIPlatformType[keyof typeof AIPlatformType];


export function instanceOfAIPlatformType(value: any): boolean {
    for (const key in AIPlatformType) {
        if (Object.prototype.hasOwnProperty.call(AIPlatformType, key)) {
            if (AIPlatformType[key as keyof typeof AIPlatformType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AIPlatformTypeFromJSON(json: any): AIPlatformType {
    return AIPlatformTypeFromJSONTyped(json, false);
}

export function AIPlatformTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AIPlatformType {
    return json as AIPlatformType;
}

export function AIPlatformTypeToJSON(value?: AIPlatformType | null): any {
    return value as any;
}

export function AIPlatformTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AIPlatformType {
    return value as AIPlatformType;
}

