/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ANTHROPICAuthConfig } from './ANTHROPICAuthConfig';
import {
    ANTHROPICAuthConfigFromJSON,
    ANTHROPICAuthConfigFromJSONTyped,
    ANTHROPICAuthConfigToJSON,
    ANTHROPICAuthConfigToJSONTyped,
} from './ANTHROPICAuthConfig';

/**
 * 
 * @export
 * @interface Anthropic
 */
export interface Anthropic {
    /**
     * Name of the connector
     * @type {string}
     * @memberof Anthropic
     */
    name: string;
    /**
     * Must be "ANTHROPIC"
     * @type {string}
     * @memberof Anthropic
     */
    type: AnthropicTypeEnum;
    /**
     * 
     * @type {ANTHROPICAuthConfig}
     * @memberof Anthropic
     */
    config: ANTHROPICAuthConfig;
}


/**
 * @export
 */
export const AnthropicTypeEnum = {
    Anthropic: 'ANTHROPIC'
} as const;
export type AnthropicTypeEnum = typeof AnthropicTypeEnum[keyof typeof AnthropicTypeEnum];


/**
 * Check if a given object implements the Anthropic interface.
 */
export function instanceOfAnthropic(value: object): value is Anthropic {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function AnthropicFromJSON(json: any): Anthropic {
    return AnthropicFromJSONTyped(json, false);
}

export function AnthropicFromJSONTyped(json: any, ignoreDiscriminator: boolean): Anthropic {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'config': ANTHROPICAuthConfigFromJSON(json['config']),
    };
}

export function AnthropicToJSON(json: any): Anthropic {
    return AnthropicToJSONTyped(json, false);
}

export function AnthropicToJSONTyped(value?: Anthropic | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'config': ANTHROPICAuthConfigToJSON(value['config']),
    };
}

