/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bedrock1
 */
export interface Bedrock1 {
    /**
     * Configuration updates
     * @type {object}
     * @memberof Bedrock1
     */
    config?: object;
}

/**
 * Check if a given object implements the Bedrock1 interface.
 */
export function instanceOfBedrock1(value: object): value is Bedrock1 {
    return true;
}

export function Bedrock1FromJSON(json: any): Bedrock1 {
    return Bedrock1FromJSONTyped(json, false);
}

export function Bedrock1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Bedrock1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function Bedrock1ToJSON(json: any): Bedrock1 {
    return Bedrock1ToJSONTyped(json, false);
}

export function Bedrock1ToJSONTyped(value?: Bedrock1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
    };
}

