/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatedDestinationConnector
 */
export interface CreatedDestinationConnector {
    /**
     * 
     * @type {string}
     * @memberof CreatedDestinationConnector
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatedDestinationConnector
     */
    id: string;
}

/**
 * Check if a given object implements the CreatedDestinationConnector interface.
 */
export function instanceOfCreatedDestinationConnector(value: object): value is CreatedDestinationConnector {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreatedDestinationConnectorFromJSON(json: any): CreatedDestinationConnector {
    return CreatedDestinationConnectorFromJSONTyped(json, false);
}

export function CreatedDestinationConnectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedDestinationConnector {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
    };
}

export function CreatedDestinationConnectorToJSON(json: any): CreatedDestinationConnector {
    return CreatedDestinationConnectorToJSONTyped(json, false);
}

export function CreatedDestinationConnectorToJSONTyped(value?: CreatedDestinationConnector | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'id': value['id'],
    };
}

