/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DATASTAXConfig } from './DATASTAXConfig';
import {
    DATASTAXConfigFromJSON,
    DATASTAXConfigFromJSONTyped,
    DATASTAXConfigToJSON,
    DATASTAXConfigToJSONTyped,
} from './DATASTAXConfig';

/**
 * 
 * @export
 * @interface Datastax
 */
export interface Datastax {
    /**
     * Name of the connector
     * @type {string}
     * @memberof Datastax
     */
    name: string;
    /**
     * Connector type (must be "DATASTAX")
     * @type {string}
     * @memberof Datastax
     */
    type: DatastaxTypeEnum;
    /**
     * 
     * @type {DATASTAXConfig}
     * @memberof Datastax
     */
    config: DATASTAXConfig;
}


/**
 * @export
 */
export const DatastaxTypeEnum = {
    Datastax: 'DATASTAX'
} as const;
export type DatastaxTypeEnum = typeof DatastaxTypeEnum[keyof typeof DatastaxTypeEnum];


/**
 * Check if a given object implements the Datastax interface.
 */
export function instanceOfDatastax(value: object): value is Datastax {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function DatastaxFromJSON(json: any): Datastax {
    return DatastaxFromJSONTyped(json, false);
}

export function DatastaxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Datastax {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'config': DATASTAXConfigFromJSON(json['config']),
    };
}

export function DatastaxToJSON(json: any): Datastax {
    return DatastaxToJSONTyped(json, false);
}

export function DatastaxToJSONTyped(value?: Datastax | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'config': DATASTAXConfigToJSON(value['config']),
    };
}

