/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for DataStax Astra
 * @export
 * @interface DATASTAXAuthConfig
 */
export interface DATASTAXAuthConfig {
    /**
     * API Endpoint. Example: Enter your API endpoint
     * @type {string}
     * @memberof DATASTAXAuthConfig
     */
    endpointSecret: string;
    /**
     * Application Token. Example: Enter your application token
     * @type {string}
     * @memberof DATASTAXAuthConfig
     */
    token: string;
}

/**
 * Check if a given object implements the DATASTAXAuthConfig interface.
 */
export function instanceOfDATASTAXAuthConfig(value: object): value is DATASTAXAuthConfig {
    if (!('endpointSecret' in value) || value['endpointSecret'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function DATASTAXAuthConfigFromJSON(json: any): DATASTAXAuthConfig {
    return DATASTAXAuthConfigFromJSONTyped(json, false);
}

export function DATASTAXAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DATASTAXAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'endpointSecret': json['endpoint_secret'],
        'token': json['token'],
    };
}

export function DATASTAXAuthConfigToJSON(json: any): DATASTAXAuthConfig {
    return DATASTAXAuthConfigToJSONTyped(json, false);
}

export function DATASTAXAuthConfigToJSONTyped(value?: DATASTAXAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoint_secret': value['endpointSecret'],
        'token': value['token'],
    };
}

