/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteFileResponse
 */
export interface DeleteFileResponse {
    /**
     * 
     * @type {string}
     * @memberof DeleteFileResponse
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteFileResponse
     */
    fileName: string;
}

/**
 * Check if a given object implements the DeleteFileResponse interface.
 */
export function instanceOfDeleteFileResponse(value: object): value is DeleteFileResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    return true;
}

export function DeleteFileResponseFromJSON(json: any): DeleteFileResponse {
    return DeleteFileResponseFromJSONTyped(json, false);
}

export function DeleteFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'fileName': json['fileName'],
    };
}

export function DeleteFileResponseToJSON(json: any): DeleteFileResponse {
    return DeleteFileResponseToJSONTyped(json, false);
}

export function DeleteFileResponseToJSONTyped(value?: DeleteFileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'fileName': value['fileName'],
    };
}

