/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeletePipelineResponse
 */
export interface DeletePipelineResponse {
    /**
     * 
     * @type {string}
     * @memberof DeletePipelineResponse
     */
    message: string;
}

/**
 * Check if a given object implements the DeletePipelineResponse interface.
 */
export function instanceOfDeletePipelineResponse(value: object): value is DeletePipelineResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeletePipelineResponseFromJSON(json: any): DeletePipelineResponse {
    return DeletePipelineResponseFromJSONTyped(json, false);
}

export function DeletePipelineResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletePipelineResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function DeletePipelineResponseToJSON(json: any): DeletePipelineResponse {
    return DeletePipelineResponseToJSONTyped(json, false);
}

export function DeletePipelineResponseToJSONTyped(value?: DeletePipelineResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

