/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DestinationConnector
 */
export interface DestinationConnector {
    /**
     * 
     * @type {string}
     * @memberof DestinationConnector
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationConnector
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationConnector
     */
    name: string;
    /**
     * 
     * @type {{ [key: string]: any | null; }}
     * @memberof DestinationConnector
     */
    configDoc?: { [key: string]: any | null; };
    /**
     * 
     * @type {string}
     * @memberof DestinationConnector
     */
    createdAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DestinationConnector
     */
    createdById?: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationConnector
     */
    lastUpdatedById?: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationConnector
     */
    createdByEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationConnector
     */
    lastUpdatedByEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationConnector
     */
    errorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof DestinationConnector
     */
    verificationStatus?: string;
}

/**
 * Check if a given object implements the DestinationConnector interface.
 */
export function instanceOfDestinationConnector(value: object): value is DestinationConnector {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DestinationConnectorFromJSON(json: any): DestinationConnector {
    return DestinationConnectorFromJSONTyped(json, false);
}

export function DestinationConnectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DestinationConnector {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'name': json['name'],
        'configDoc': json['configDoc'] == null ? undefined : json['configDoc'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'createdById': json['createdById'] == null ? undefined : json['createdById'],
        'lastUpdatedById': json['lastUpdatedById'] == null ? undefined : json['lastUpdatedById'],
        'createdByEmail': json['createdByEmail'] == null ? undefined : json['createdByEmail'],
        'lastUpdatedByEmail': json['lastUpdatedByEmail'] == null ? undefined : json['lastUpdatedByEmail'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'verificationStatus': json['verificationStatus'] == null ? undefined : json['verificationStatus'],
    };
}

export function DestinationConnectorToJSON(json: any): DestinationConnector {
    return DestinationConnectorToJSONTyped(json, false);
}

export function DestinationConnectorToJSONTyped(value?: DestinationConnector | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'name': value['name'],
        'configDoc': value['configDoc'],
        'createdAt': value['createdAt'],
        'createdById': value['createdById'],
        'lastUpdatedById': value['lastUpdatedById'],
        'createdByEmail': value['createdByEmail'],
        'lastUpdatedByEmail': value['lastUpdatedByEmail'],
        'errorMessage': value['errorMessage'],
        'verificationStatus': value['verificationStatus'],
    };
}

