/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DestinationConnectorType = {
    Capella: 'CAPELLA',
    Datastax: 'DATASTAX',
    Elastic: 'ELASTIC',
    Pinecone: 'PINECONE',
    Azureaisearch: 'AZUREAISEARCH',
    Milvus: 'MILVUS',
    Neo4J: 'NEO4J',
    Postgresql: 'POSTGRESQL',
    Qdrant: 'QDRANT',
    Singlestore: 'SINGLESTORE',
    Supabase: 'SUPABASE',
    Turbopuffer: 'TURBOPUFFER',
    Weaviate: 'WEAVIATE'
} as const;
export type DestinationConnectorType = typeof DestinationConnectorType[keyof typeof DestinationConnectorType];


export function instanceOfDestinationConnectorType(value: any): boolean {
    for (const key in DestinationConnectorType) {
        if (Object.prototype.hasOwnProperty.call(DestinationConnectorType, key)) {
            if (DestinationConnectorType[key as keyof typeof DestinationConnectorType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DestinationConnectorTypeFromJSON(json: any): DestinationConnectorType {
    return DestinationConnectorTypeFromJSONTyped(json, false);
}

export function DestinationConnectorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DestinationConnectorType {
    return json as DestinationConnectorType;
}

export function DestinationConnectorTypeToJSON(value?: DestinationConnectorType | null): any {
    return value as any;
}

export function DestinationConnectorTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DestinationConnectorType {
    return value as DestinationConnectorType;
}

