/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DROPBOXConfig } from './DROPBOXConfig';
import {
    DROPBOXConfigFromJSON,
    DROPBOXConfigFromJSONTyped,
    DROPBOXConfigToJSON,
    DROPBOXConfigToJSONTyped,
} from './DROPBOXConfig';

/**
 * 
 * @export
 * @interface Dropbox
 */
export interface Dropbox {
    /**
     * 
     * @type {DROPBOXConfig}
     * @memberof Dropbox
     */
    config?: DROPBOXConfig;
}

/**
 * Check if a given object implements the Dropbox interface.
 */
export function instanceOfDropbox(value: object): value is Dropbox {
    return true;
}

export function DropboxFromJSON(json: any): Dropbox {
    return DropboxFromJSONTyped(json, false);
}

export function DropboxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Dropbox {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : DROPBOXConfigFromJSON(json['config']),
    };
}

export function DropboxToJSON(json: any): Dropbox {
    return DropboxToJSONTyped(json, false);
}

export function DropboxToJSONTyped(value?: Dropbox | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': DROPBOXConfigToJSON(value['config']),
    };
}

