/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for Dropbox Multi-User (White Label)
 * @export
 * @interface DROPBOXOAUTHMULTICUSTOMAuthConfig
 */
export interface DROPBOXOAUTHMULTICUSTOMAuthConfig {
    /**
     * Dropbox App Key. Example: Enter App Key
     * @type {string}
     * @memberof DROPBOXOAUTHMULTICUSTOMAuthConfig
     */
    appKey: string;
    /**
     * Dropbox App Secret. Example: Enter App Secret
     * @type {string}
     * @memberof DROPBOXOAUTHMULTICUSTOMAuthConfig
     */
    appSecret: string;
    /**
     * Authorized Users
     * @type {Array<string>}
     * @memberof DROPBOXOAUTHMULTICUSTOMAuthConfig
     */
    authorizedUsers?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof DROPBOXOAUTHMULTICUSTOMAuthConfig
     */
    editedUsers?: object;
    /**
     * 
     * @type {object}
     * @memberof DROPBOXOAUTHMULTICUSTOMAuthConfig
     */
    deletedUsers?: object;
}

/**
 * Check if a given object implements the DROPBOXOAUTHMULTICUSTOMAuthConfig interface.
 */
export function instanceOfDROPBOXOAUTHMULTICUSTOMAuthConfig(value: object): value is DROPBOXOAUTHMULTICUSTOMAuthConfig {
    if (!('appKey' in value) || value['appKey'] === undefined) return false;
    if (!('appSecret' in value) || value['appSecret'] === undefined) return false;
    return true;
}

export function DROPBOXOAUTHMULTICUSTOMAuthConfigFromJSON(json: any): DROPBOXOAUTHMULTICUSTOMAuthConfig {
    return DROPBOXOAUTHMULTICUSTOMAuthConfigFromJSONTyped(json, false);
}

export function DROPBOXOAUTHMULTICUSTOMAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DROPBOXOAUTHMULTICUSTOMAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'appKey': json['app-key'],
        'appSecret': json['app-secret'],
        'authorizedUsers': json['authorized-users'] == null ? undefined : json['authorized-users'],
        'editedUsers': json['editedUsers'] == null ? undefined : json['editedUsers'],
        'deletedUsers': json['deletedUsers'] == null ? undefined : json['deletedUsers'],
    };
}

export function DROPBOXOAUTHMULTICUSTOMAuthConfigToJSON(json: any): DROPBOXOAUTHMULTICUSTOMAuthConfig {
    return DROPBOXOAUTHMULTICUSTOMAuthConfigToJSONTyped(json, false);
}

export function DROPBOXOAUTHMULTICUSTOMAuthConfigToJSONTyped(value?: DROPBOXOAUTHMULTICUSTOMAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app-key': value['appKey'],
        'app-secret': value['appSecret'],
        'authorized-users': value['authorizedUsers'],
        'editedUsers': value['editedUsers'],
        'deletedUsers': value['deletedUsers'],
    };
}

