/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtractionResult } from './ExtractionResult';
import {
    ExtractionResultFromJSON,
    ExtractionResultFromJSONTyped,
    ExtractionResultToJSON,
    ExtractionResultToJSONTyped,
} from './ExtractionResult';

/**
 * 
 * @export
 * @interface ExtractionResultResponse
 */
export interface ExtractionResultResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ExtractionResultResponse
     */
    ready: boolean;
    /**
     * 
     * @type {ExtractionResult}
     * @memberof ExtractionResultResponse
     */
    data?: ExtractionResult;
}

/**
 * Check if a given object implements the ExtractionResultResponse interface.
 */
export function instanceOfExtractionResultResponse(value: object): value is ExtractionResultResponse {
    if (!('ready' in value) || value['ready'] === undefined) return false;
    return true;
}

export function ExtractionResultResponseFromJSON(json: any): ExtractionResultResponse {
    return ExtractionResultResponseFromJSONTyped(json, false);
}

export function ExtractionResultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractionResultResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ready': json['ready'],
        'data': json['data'] == null ? undefined : ExtractionResultFromJSON(json['data']),
    };
}

export function ExtractionResultResponseToJSON(json: any): ExtractionResultResponse {
    return ExtractionResultResponseToJSONTyped(json, false);
}

export function ExtractionResultResponseToJSONTyped(value?: ExtractionResultResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ready': value['ready'],
        'data': ExtractionResultToJSON(value['data']),
    };
}

