/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FIREFLIESAuthConfig } from './FIREFLIESAuthConfig';
import {
    FIREFLIESAuthConfigFromJSON,
    FIREFLIESAuthConfigFromJSONTyped,
    FIREFLIESAuthConfigToJSON,
    FIREFLIESAuthConfigToJSONTyped,
} from './FIREFLIESAuthConfig';

/**
 * 
 * @export
 * @interface Fireflies1
 */
export interface Fireflies1 {
    /**
     * 
     * @type {FIREFLIESAuthConfig}
     * @memberof Fireflies1
     */
    config?: FIREFLIESAuthConfig;
}

/**
 * Check if a given object implements the Fireflies1 interface.
 */
export function instanceOfFireflies1(value: object): value is Fireflies1 {
    return true;
}

export function Fireflies1FromJSON(json: any): Fireflies1 {
    return Fireflies1FromJSONTyped(json, false);
}

export function Fireflies1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Fireflies1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : FIREFLIESAuthConfigFromJSON(json['config']),
    };
}

export function Fireflies1ToJSON(json: any): Fireflies1 {
    return Fireflies1ToJSONTyped(json, false);
}

export function Fireflies1ToJSONTyped(value?: Fireflies1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': FIREFLIESAuthConfigToJSON(value['config']),
    };
}

