/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FIREFLIESAuthConfig } from './FIREFLIESAuthConfig';
import {
    FIREFLIESAuthConfigFromJSON,
    FIREFLIESAuthConfigFromJSONTyped,
    FIREFLIESAuthConfigToJSON,
    FIREFLIESAuthConfigToJSONTyped,
} from './FIREFLIESAuthConfig';

/**
 * 
 * @export
 * @interface Fireflies
 */
export interface Fireflies {
    /**
     * Name of the connector
     * @type {string}
     * @memberof Fireflies
     */
    name: string;
    /**
     * Connector type (must be "FIREFLIES")
     * @type {string}
     * @memberof Fireflies
     */
    type: FirefliesTypeEnum;
    /**
     * 
     * @type {FIREFLIESAuthConfig}
     * @memberof Fireflies
     */
    config: FIREFLIESAuthConfig;
}


/**
 * @export
 */
export const FirefliesTypeEnum = {
    Fireflies: 'FIREFLIES'
} as const;
export type FirefliesTypeEnum = typeof FirefliesTypeEnum[keyof typeof FirefliesTypeEnum];


/**
 * Check if a given object implements the Fireflies interface.
 */
export function instanceOfFireflies(value: object): value is Fireflies {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function FirefliesFromJSON(json: any): Fireflies {
    return FirefliesFromJSONTyped(json, false);
}

export function FirefliesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Fireflies {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'config': FIREFLIESAuthConfigFromJSON(json['config']),
    };
}

export function FirefliesToJSON(json: any): Fireflies {
    return FirefliesToJSONTyped(json, false);
}

export function FirefliesToJSONTyped(value?: Fireflies | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'config': FIREFLIESAuthConfigToJSON(value['config']),
    };
}

