/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FIRECRAWLAuthConfig } from './FIRECRAWLAuthConfig';
import {
    FIRECRAWLAuthConfigFromJSON,
    FIRECRAWLAuthConfigFromJSONTyped,
    FIRECRAWLAuthConfigToJSON,
    FIRECRAWLAuthConfigToJSONTyped,
} from './FIRECRAWLAuthConfig';

/**
 * 
 * @export
 * @interface Firecrawl1
 */
export interface Firecrawl1 {
    /**
     * 
     * @type {FIRECRAWLAuthConfig}
     * @memberof Firecrawl1
     */
    config?: FIRECRAWLAuthConfig;
}

/**
 * Check if a given object implements the Firecrawl1 interface.
 */
export function instanceOfFirecrawl1(value: object): value is Firecrawl1 {
    return true;
}

export function Firecrawl1FromJSON(json: any): Firecrawl1 {
    return Firecrawl1FromJSONTyped(json, false);
}

export function Firecrawl1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Firecrawl1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : FIRECRAWLAuthConfigFromJSON(json['config']),
    };
}

export function Firecrawl1ToJSON(json: any): Firecrawl1 {
    return Firecrawl1ToJSONTyped(json, false);
}

export function Firecrawl1ToJSONTyped(value?: Firecrawl1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': FIRECRAWLAuthConfigToJSON(value['config']),
    };
}

