/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for Fireflies.ai
 * @export
 * @interface FIREFLIESAuthConfig
 */
export interface FIREFLIESAuthConfig {
    /**
     * API Key. Example: Enter your Fireflies.ai API key
     * @type {string}
     * @memberof FIREFLIESAuthConfig
     */
    apiKey: string;
}

/**
 * Check if a given object implements the FIREFLIESAuthConfig interface.
 */
export function instanceOfFIREFLIESAuthConfig(value: object): value is FIREFLIESAuthConfig {
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function FIREFLIESAuthConfigFromJSON(json: any): FIREFLIESAuthConfig {
    return FIREFLIESAuthConfigFromJSONTyped(json, false);
}

export function FIREFLIESAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): FIREFLIESAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api-key'],
    };
}

export function FIREFLIESAuthConfigToJSON(json: any): FIREFLIESAuthConfig {
    return FIREFLIESAuthConfigToJSONTyped(json, false);
}

export function FIREFLIESAuthConfigToJSONTyped(value?: FIREFLIESAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api-key': value['apiKey'],
    };
}

