/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DestinationConnector } from './DestinationConnector';
import {
    DestinationConnectorFromJSON,
    DestinationConnectorFromJSONTyped,
    DestinationConnectorToJSON,
    DestinationConnectorToJSONTyped,
} from './DestinationConnector';

/**
 * 
 * @export
 * @interface GetDestinationConnectors200Response
 */
export interface GetDestinationConnectors200Response {
    /**
     * 
     * @type {Array<DestinationConnector>}
     * @memberof GetDestinationConnectors200Response
     */
    destinationConnectors: Array<DestinationConnector>;
}

/**
 * Check if a given object implements the GetDestinationConnectors200Response interface.
 */
export function instanceOfGetDestinationConnectors200Response(value: object): value is GetDestinationConnectors200Response {
    if (!('destinationConnectors' in value) || value['destinationConnectors'] === undefined) return false;
    return true;
}

export function GetDestinationConnectors200ResponseFromJSON(json: any): GetDestinationConnectors200Response {
    return GetDestinationConnectors200ResponseFromJSONTyped(json, false);
}

export function GetDestinationConnectors200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDestinationConnectors200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationConnectors': ((json['destinationConnectors'] as Array<any>).map(DestinationConnectorFromJSON)),
    };
}

export function GetDestinationConnectors200ResponseToJSON(json: any): GetDestinationConnectors200Response {
    return GetDestinationConnectors200ResponseToJSONTyped(json, false);
}

export function GetDestinationConnectors200ResponseToJSONTyped(value?: GetDestinationConnectors200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destinationConnectors': ((value['destinationConnectors'] as Array<any>).map(DestinationConnectorToJSON)),
    };
}

