/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeepResearchResult } from './DeepResearchResult';
import {
    DeepResearchResultFromJSON,
    DeepResearchResultFromJSONTyped,
    DeepResearchResultToJSON,
    DeepResearchResultToJSONTyped,
} from './DeepResearchResult';

/**
 * 
 * @export
 * @interface GetDeepResearchResponse
 */
export interface GetDeepResearchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetDeepResearchResponse
     */
    ready: boolean;
    /**
     * 
     * @type {DeepResearchResult}
     * @memberof GetDeepResearchResponse
     */
    data?: DeepResearchResult;
}

/**
 * Check if a given object implements the GetDeepResearchResponse interface.
 */
export function instanceOfGetDeepResearchResponse(value: object): value is GetDeepResearchResponse {
    if (!('ready' in value) || value['ready'] === undefined) return false;
    return true;
}

export function GetDeepResearchResponseFromJSON(json: any): GetDeepResearchResponse {
    return GetDeepResearchResponseFromJSONTyped(json, false);
}

export function GetDeepResearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDeepResearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ready': json['ready'],
        'data': json['data'] == null ? undefined : DeepResearchResultFromJSON(json['data']),
    };
}

export function GetDeepResearchResponseToJSON(json: any): GetDeepResearchResponse {
    return GetDeepResearchResponseToJSONTyped(json, false);
}

export function GetDeepResearchResponseToJSONTyped(value?: GetDeepResearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ready': value['ready'],
        'data': DeepResearchResultToJSON(value['data']),
    };
}

