/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API (Beta)
 * API documentation for Vectorize services
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPipelines400Response
 */
export interface GetPipelines400Response {
    /**
     * 
     * @type {string}
     * @memberof GetPipelines400Response
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof GetPipelines400Response
     */
    details?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetPipelines400Response
     */
    failedUpdates?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetPipelines400Response
     */
    successfulUpdates?: Array<string>;
}

/**
 * Check if a given object implements the GetPipelines400Response interface.
 */
export function instanceOfGetPipelines400Response(value: object): value is GetPipelines400Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function GetPipelines400ResponseFromJSON(json: any): GetPipelines400Response {
    return GetPipelines400ResponseFromJSONTyped(json, false);
}

export function GetPipelines400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPipelines400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
        'details': json['details'] == null ? undefined : json['details'],
        'failedUpdates': json['failedUpdates'] == null ? undefined : json['failedUpdates'],
        'successfulUpdates': json['successfulUpdates'] == null ? undefined : json['successfulUpdates'],
    };
}

export function GetPipelines400ResponseToJSON(json: any): GetPipelines400Response {
    return GetPipelines400ResponseToJSONTyped(json, false);
}

export function GetPipelines400ResponseToJSONTyped(value?: GetPipelines400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'details': value['details'],
        'failedUpdates': value['failedUpdates'],
        'successfulUpdates': value['successfulUpdates'],
    };
}

