/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PipelineMetrics } from './PipelineMetrics';
import {
    PipelineMetricsFromJSON,
    PipelineMetricsFromJSONTyped,
    PipelineMetricsToJSON,
    PipelineMetricsToJSONTyped,
} from './PipelineMetrics';

/**
 * 
 * @export
 * @interface GetPipelineMetricsResponse
 */
export interface GetPipelineMetricsResponse {
    /**
     * 
     * @type {string}
     * @memberof GetPipelineMetricsResponse
     */
    message: string;
    /**
     * 
     * @type {Array<PipelineMetrics>}
     * @memberof GetPipelineMetricsResponse
     */
    data: Array<PipelineMetrics>;
}

/**
 * Check if a given object implements the GetPipelineMetricsResponse interface.
 */
export function instanceOfGetPipelineMetricsResponse(value: object): value is GetPipelineMetricsResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetPipelineMetricsResponseFromJSON(json: any): GetPipelineMetricsResponse {
    return GetPipelineMetricsResponseFromJSONTyped(json, false);
}

export function GetPipelineMetricsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPipelineMetricsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': ((json['data'] as Array<any>).map(PipelineMetricsFromJSON)),
    };
}

export function GetPipelineMetricsResponseToJSON(json: any): GetPipelineMetricsResponse {
    return GetPipelineMetricsResponseToJSONTyped(json, false);
}

export function GetPipelineMetricsResponseToJSONTyped(value?: GetPipelineMetricsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': ((value['data'] as Array<any>).map(PipelineMetricsToJSON)),
    };
}

