/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PipelineListSummary } from './PipelineListSummary';
import {
    PipelineListSummaryFromJSON,
    PipelineListSummaryFromJSONTyped,
    PipelineListSummaryToJSON,
    PipelineListSummaryToJSONTyped,
} from './PipelineListSummary';

/**
 * 
 * @export
 * @interface GetPipelinesResponse
 */
export interface GetPipelinesResponse {
    /**
     * 
     * @type {string}
     * @memberof GetPipelinesResponse
     */
    message: string;
    /**
     * 
     * @type {Array<PipelineListSummary>}
     * @memberof GetPipelinesResponse
     */
    data: Array<PipelineListSummary>;
}

/**
 * Check if a given object implements the GetPipelinesResponse interface.
 */
export function instanceOfGetPipelinesResponse(value: object): value is GetPipelinesResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetPipelinesResponseFromJSON(json: any): GetPipelinesResponse {
    return GetPipelinesResponseFromJSONTyped(json, false);
}

export function GetPipelinesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPipelinesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': ((json['data'] as Array<any>).map(PipelineListSummaryFromJSON)),
    };
}

export function GetPipelinesResponseToJSON(json: any): GetPipelinesResponse {
    return GetPipelinesResponseToJSONTyped(json, false);
}

export function GetPipelinesResponseToJSONTyped(value?: GetPipelinesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': ((value['data'] as Array<any>).map(PipelineListSummaryToJSON)),
    };
}

