/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GITHUBConfig } from './GITHUBConfig';
import {
    GITHUBConfigFromJSON,
    GITHUBConfigFromJSONTyped,
    GITHUBConfigToJSON,
    GITHUBConfigToJSONTyped,
} from './GITHUBConfig';

/**
 * 
 * @export
 * @interface Github1
 */
export interface Github1 {
    /**
     * 
     * @type {GITHUBConfig}
     * @memberof Github1
     */
    config?: GITHUBConfig;
}

/**
 * Check if a given object implements the Github1 interface.
 */
export function instanceOfGithub1(value: object): value is Github1 {
    return true;
}

export function Github1FromJSON(json: any): Github1 {
    return Github1FromJSONTyped(json, false);
}

export function Github1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Github1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : GITHUBConfigFromJSON(json['config']),
    };
}

export function Github1ToJSON(json: any): Github1 {
    return Github1ToJSONTyped(json, false);
}

export function Github1ToJSONTyped(value?: Github1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': GITHUBConfigToJSON(value['config']),
    };
}

