/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for Gmail
 * @export
 * @interface GMAILAuthConfig
 */
export interface GMAILAuthConfig {
    /**
     * Connect Gmail to Vectorize. Example: Authorize
     * @type {string}
     * @memberof GMAILAuthConfig
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the GMAILAuthConfig interface.
 */
export function instanceOfGMAILAuthConfig(value: object): value is GMAILAuthConfig {
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    return true;
}

export function GMAILAuthConfigFromJSON(json: any): GMAILAuthConfig {
    return GMAILAuthConfigFromJSONTyped(json, false);
}

export function GMAILAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GMAILAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refresh-token'],
    };
}

export function GMAILAuthConfigToJSON(json: any): GMAILAuthConfig {
    return GMAILAuthConfigToJSONTyped(json, false);
}

export function GMAILAuthConfigToJSONTyped(value?: GMAILAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refresh-token': value['refreshToken'],
    };
}

