/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for Google Drive OAuth
 * @export
 * @interface GOOGLEDRIVEOAUTHAuthConfig
 */
export interface GOOGLEDRIVEOAUTHAuthConfig {
    /**
     * Authorized User
     * @type {string}
     * @memberof GOOGLEDRIVEOAUTHAuthConfig
     */
    authorizedUser?: string;
    /**
     * Connect Google Drive to Vectorize. Example: Authorize
     * @type {string}
     * @memberof GOOGLEDRIVEOAUTHAuthConfig
     */
    selectionDetails: string;
    /**
     * 
     * @type {object}
     * @memberof GOOGLEDRIVEOAUTHAuthConfig
     */
    editedUsers?: object;
    /**
     * 
     * @type {object}
     * @memberof GOOGLEDRIVEOAUTHAuthConfig
     */
    reconnectUsers?: object;
}

/**
 * Check if a given object implements the GOOGLEDRIVEOAUTHAuthConfig interface.
 */
export function instanceOfGOOGLEDRIVEOAUTHAuthConfig(value: object): value is GOOGLEDRIVEOAUTHAuthConfig {
    if (!('selectionDetails' in value) || value['selectionDetails'] === undefined) return false;
    return true;
}

export function GOOGLEDRIVEOAUTHAuthConfigFromJSON(json: any): GOOGLEDRIVEOAUTHAuthConfig {
    return GOOGLEDRIVEOAUTHAuthConfigFromJSONTyped(json, false);
}

export function GOOGLEDRIVEOAUTHAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GOOGLEDRIVEOAUTHAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'authorizedUser': json['authorized-user'] == null ? undefined : json['authorized-user'],
        'selectionDetails': json['selection-details'],
        'editedUsers': json['editedUsers'] == null ? undefined : json['editedUsers'],
        'reconnectUsers': json['reconnectUsers'] == null ? undefined : json['reconnectUsers'],
    };
}

export function GOOGLEDRIVEOAUTHAuthConfigToJSON(json: any): GOOGLEDRIVEOAUTHAuthConfig {
    return GOOGLEDRIVEOAUTHAuthConfigToJSONTyped(json, false);
}

export function GOOGLEDRIVEOAUTHAuthConfigToJSONTyped(value?: GOOGLEDRIVEOAUTHAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorized-user': value['authorizedUser'],
        'selection-details': value['selectionDetails'],
        'editedUsers': value['editedUsers'],
        'reconnectUsers': value['reconnectUsers'],
    };
}

