/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for Google Drive Multi-User (Vectorize)
 * @export
 * @interface GOOGLEDRIVEOAUTHMULTIAuthConfig
 */
export interface GOOGLEDRIVEOAUTHMULTIAuthConfig {
    /**
     * Name. Example: Enter a descriptive name
     * @type {string}
     * @memberof GOOGLEDRIVEOAUTHMULTIAuthConfig
     */
    name: string;
    /**
     * Authorized Users
     * @type {string}
     * @memberof GOOGLEDRIVEOAUTHMULTIAuthConfig
     */
    authorizedUsers?: string;
    /**
     * 
     * @type {object}
     * @memberof GOOGLEDRIVEOAUTHMULTIAuthConfig
     */
    editedUsers?: object;
    /**
     * 
     * @type {object}
     * @memberof GOOGLEDRIVEOAUTHMULTIAuthConfig
     */
    deletedUsers?: object;
}

/**
 * Check if a given object implements the GOOGLEDRIVEOAUTHMULTIAuthConfig interface.
 */
export function instanceOfGOOGLEDRIVEOAUTHMULTIAuthConfig(value: object): value is GOOGLEDRIVEOAUTHMULTIAuthConfig {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GOOGLEDRIVEOAUTHMULTIAuthConfigFromJSON(json: any): GOOGLEDRIVEOAUTHMULTIAuthConfig {
    return GOOGLEDRIVEOAUTHMULTIAuthConfigFromJSONTyped(json, false);
}

export function GOOGLEDRIVEOAUTHMULTIAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GOOGLEDRIVEOAUTHMULTIAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'authorizedUsers': json['authorized-users'] == null ? undefined : json['authorized-users'],
        'editedUsers': json['editedUsers'] == null ? undefined : json['editedUsers'],
        'deletedUsers': json['deletedUsers'] == null ? undefined : json['deletedUsers'],
    };
}

export function GOOGLEDRIVEOAUTHMULTIAuthConfigToJSON(json: any): GOOGLEDRIVEOAUTHMULTIAuthConfig {
    return GOOGLEDRIVEOAUTHMULTIAuthConfigToJSONTyped(json, false);
}

export function GOOGLEDRIVEOAUTHMULTIAuthConfigToJSONTyped(value?: GOOGLEDRIVEOAUTHMULTIAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'authorized-users': value['authorizedUsers'],
        'editedUsers': value['editedUsers'],
        'deletedUsers': value['deletedUsers'],
    };
}

