/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GOOGLEDRIVEOAUTHAuthConfig } from './GOOGLEDRIVEOAUTHAuthConfig';
import {
    GOOGLEDRIVEOAUTHAuthConfigFromJSON,
    GOOGLEDRIVEOAUTHAuthConfigFromJSONTyped,
    GOOGLEDRIVEOAUTHAuthConfigToJSON,
    GOOGLEDRIVEOAUTHAuthConfigToJSONTyped,
} from './GOOGLEDRIVEOAUTHAuthConfig';

/**
 * 
 * @export
 * @interface GoogleDriveOauth
 */
export interface GoogleDriveOauth {
    /**
     * 
     * @type {GOOGLEDRIVEOAUTHAuthConfig}
     * @memberof GoogleDriveOauth
     */
    config?: GOOGLEDRIVEOAUTHAuthConfig;
}

/**
 * Check if a given object implements the GoogleDriveOauth interface.
 */
export function instanceOfGoogleDriveOauth(value: object): value is GoogleDriveOauth {
    return true;
}

export function GoogleDriveOauthFromJSON(json: any): GoogleDriveOauth {
    return GoogleDriveOauthFromJSONTyped(json, false);
}

export function GoogleDriveOauthFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleDriveOauth {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : GOOGLEDRIVEOAUTHAuthConfigFromJSON(json['config']),
    };
}

export function GoogleDriveOauthToJSON(json: any): GoogleDriveOauth {
    return GoogleDriveOauthToJSONTyped(json, false);
}

export function GoogleDriveOauthToJSONTyped(value?: GoogleDriveOauth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': GOOGLEDRIVEOAUTHAuthConfigToJSON(value['config']),
    };
}

