/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for Groq
 * @export
 * @interface GROQAuthConfig
 */
export interface GROQAuthConfig {
    /**
     * API Key. Example: Enter your Groq API Key
     * @type {string}
     * @memberof GROQAuthConfig
     */
    key: string;
}

/**
 * Check if a given object implements the GROQAuthConfig interface.
 */
export function instanceOfGROQAuthConfig(value: object): value is GROQAuthConfig {
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function GROQAuthConfigFromJSON(json: any): GROQAuthConfig {
    return GROQAuthConfigFromJSONTyped(json, false);
}

export function GROQAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GROQAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
    };
}

export function GROQAuthConfigToJSON(json: any): GROQAuthConfig {
    return GROQAuthConfigToJSONTyped(json, false);
}

export function GROQAuthConfigToJSONTyped(value?: GROQAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
    };
}

