/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Groq1
 */
export interface Groq1 {
    /**
     * Configuration updates
     * @type {object}
     * @memberof Groq1
     */
    config?: object;
}

/**
 * Check if a given object implements the Groq1 interface.
 */
export function instanceOfGroq1(value: object): value is Groq1 {
    return true;
}

export function Groq1FromJSON(json: any): Groq1 {
    return Groq1FromJSONTyped(json, false);
}

export function Groq1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Groq1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function Groq1ToJSON(json: any): Groq1 {
    return Groq1ToJSONTyped(json, false);
}

export function Groq1ToJSONTyped(value?: Groq1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
    };
}

