/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEO4JAuthConfig } from './NEO4JAuthConfig';
import {
    NEO4JAuthConfigFromJSON,
    NEO4JAuthConfigFromJSONTyped,
    NEO4JAuthConfigToJSON,
    NEO4JAuthConfigToJSONTyped,
} from './NEO4JAuthConfig';

/**
 * 
 * @export
 * @interface Neo4j1
 */
export interface Neo4j1 {
    /**
     * 
     * @type {NEO4JAuthConfig}
     * @memberof Neo4j1
     */
    config?: NEO4JAuthConfig;
}

/**
 * Check if a given object implements the Neo4j1 interface.
 */
export function instanceOfNeo4j1(value: object): value is Neo4j1 {
    return true;
}

export function Neo4j1FromJSON(json: any): Neo4j1 {
    return Neo4j1FromJSONTyped(json, false);
}

export function Neo4j1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Neo4j1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : NEO4JAuthConfigFromJSON(json['config']),
    };
}

export function Neo4j1ToJSON(json: any): Neo4j1 {
    return Neo4j1ToJSONTyped(json, false);
}

export function Neo4j1ToJSONTyped(value?: Neo4j1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': NEO4JAuthConfigToJSON(value['config']),
    };
}

