/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for Notion Multi-User (White Label)
 * @export
 * @interface NOTIONOAUTHMULTICUSTOMAuthConfig
 */
export interface NOTIONOAUTHMULTICUSTOMAuthConfig {
    /**
     * Name. Example: Enter a descriptive name
     * @type {string}
     * @memberof NOTIONOAUTHMULTICUSTOMAuthConfig
     */
    name: string;
    /**
     * Notion Client ID. Example: Enter Client ID
     * @type {string}
     * @memberof NOTIONOAUTHMULTICUSTOMAuthConfig
     */
    clientId: string;
    /**
     * Notion Client Secret. Example: Enter Client Secret
     * @type {string}
     * @memberof NOTIONOAUTHMULTICUSTOMAuthConfig
     */
    clientSecret: string;
    /**
     * Authorized Users
     * @type {string}
     * @memberof NOTIONOAUTHMULTICUSTOMAuthConfig
     */
    authorizedUsers?: string;
    /**
     * 
     * @type {object}
     * @memberof NOTIONOAUTHMULTICUSTOMAuthConfig
     */
    editedUsers?: object;
    /**
     * 
     * @type {object}
     * @memberof NOTIONOAUTHMULTICUSTOMAuthConfig
     */
    deletedUsers?: object;
}

/**
 * Check if a given object implements the NOTIONOAUTHMULTICUSTOMAuthConfig interface.
 */
export function instanceOfNOTIONOAUTHMULTICUSTOMAuthConfig(value: object): value is NOTIONOAUTHMULTICUSTOMAuthConfig {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('clientSecret' in value) || value['clientSecret'] === undefined) return false;
    return true;
}

export function NOTIONOAUTHMULTICUSTOMAuthConfigFromJSON(json: any): NOTIONOAUTHMULTICUSTOMAuthConfig {
    return NOTIONOAUTHMULTICUSTOMAuthConfigFromJSONTyped(json, false);
}

export function NOTIONOAUTHMULTICUSTOMAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): NOTIONOAUTHMULTICUSTOMAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'clientId': json['client-id'],
        'clientSecret': json['client-secret'],
        'authorizedUsers': json['authorized-users'] == null ? undefined : json['authorized-users'],
        'editedUsers': json['editedUsers'] == null ? undefined : json['editedUsers'],
        'deletedUsers': json['deletedUsers'] == null ? undefined : json['deletedUsers'],
    };
}

export function NOTIONOAUTHMULTICUSTOMAuthConfigToJSON(json: any): NOTIONOAUTHMULTICUSTOMAuthConfig {
    return NOTIONOAUTHMULTICUSTOMAuthConfigToJSONTyped(json, false);
}

export function NOTIONOAUTHMULTICUSTOMAuthConfigToJSONTyped(value?: NOTIONOAUTHMULTICUSTOMAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'client-id': value['clientId'],
        'client-secret': value['clientSecret'],
        'authorized-users': value['authorizedUsers'],
        'editedUsers': value['editedUsers'],
        'deletedUsers': value['deletedUsers'],
    };
}

