/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ONEDRIVEAuthConfig } from './ONEDRIVEAuthConfig';
import {
    ONEDRIVEAuthConfigFromJSON,
    ONEDRIVEAuthConfigFromJSONTyped,
    ONEDRIVEAuthConfigToJSON,
    ONEDRIVEAuthConfigToJSONTyped,
} from './ONEDRIVEAuthConfig';

/**
 * 
 * @export
 * @interface OneDrive1
 */
export interface OneDrive1 {
    /**
     * 
     * @type {ONEDRIVEAuthConfig}
     * @memberof OneDrive1
     */
    config?: ONEDRIVEAuthConfig;
}

/**
 * Check if a given object implements the OneDrive1 interface.
 */
export function instanceOfOneDrive1(value: object): value is OneDrive1 {
    return true;
}

export function OneDrive1FromJSON(json: any): OneDrive1 {
    return OneDrive1FromJSONTyped(json, false);
}

export function OneDrive1FromJSONTyped(json: any, ignoreDiscriminator: boolean): OneDrive1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : ONEDRIVEAuthConfigFromJSON(json['config']),
    };
}

export function OneDrive1ToJSON(json: any): OneDrive1 {
    return OneDrive1ToJSONTyped(json, false);
}

export function OneDrive1ToJSONTyped(value?: OneDrive1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': ONEDRIVEAuthConfigToJSON(value['config']),
    };
}

