/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Openai1
 */
export interface Openai1 {
    /**
     * Configuration updates
     * @type {object}
     * @memberof Openai1
     */
    config?: object;
}

/**
 * Check if a given object implements the Openai1 interface.
 */
export function instanceOfOpenai1(value: object): value is Openai1 {
    return true;
}

export function Openai1FromJSON(json: any): Openai1 {
    return Openai1FromJSONTyped(json, false);
}

export function Openai1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Openai1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function Openai1ToJSON(json: any): Openai1 {
    return Openai1ToJSONTyped(json, false);
}

export function Openai1ToJSONTyped(value?: Openai1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
    };
}

