/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PINECONEAuthConfig } from './PINECONEAuthConfig';
import {
    PINECONEAuthConfigFromJSON,
    PINECONEAuthConfigFromJSONTyped,
    PINECONEAuthConfigToJSON,
    PINECONEAuthConfigToJSONTyped,
} from './PINECONEAuthConfig';

/**
 * 
 * @export
 * @interface Pinecone
 */
export interface Pinecone {
    /**
     * Name of the connector
     * @type {string}
     * @memberof Pinecone
     */
    name: string;
    /**
     * Connector type (must be "PINECONE")
     * @type {string}
     * @memberof Pinecone
     */
    type: PineconeTypeEnum;
    /**
     * 
     * @type {PINECONEAuthConfig}
     * @memberof Pinecone
     */
    config: PINECONEAuthConfig;
}


/**
 * @export
 */
export const PineconeTypeEnum = {
    Pinecone: 'PINECONE'
} as const;
export type PineconeTypeEnum = typeof PineconeTypeEnum[keyof typeof PineconeTypeEnum];


/**
 * Check if a given object implements the Pinecone interface.
 */
export function instanceOfPinecone(value: object): value is Pinecone {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function PineconeFromJSON(json: any): Pinecone {
    return PineconeFromJSONTyped(json, false);
}

export function PineconeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pinecone {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'config': PINECONEAuthConfigFromJSON(json['config']),
    };
}

export function PineconeToJSON(json: any): Pinecone {
    return PineconeToJSONTyped(json, false);
}

export function PineconeToJSONTyped(value?: Pinecone | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'config': PINECONEAuthConfigToJSON(value['config']),
    };
}

