/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for Pinecone
 * @export
 * @interface PINECONEAuthConfig
 */
export interface PINECONEAuthConfig {
    /**
     * Name. Example: Enter a descriptive name for your Pinecone integration
     * @type {string}
     * @memberof PINECONEAuthConfig
     */
    name: string;
    /**
     * API Key. Example: Enter your API Key
     * @type {string}
     * @memberof PINECONEAuthConfig
     */
    apiKey: string;
}

/**
 * Check if a given object implements the PINECONEAuthConfig interface.
 */
export function instanceOfPINECONEAuthConfig(value: object): value is PINECONEAuthConfig {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function PINECONEAuthConfigFromJSON(json: any): PINECONEAuthConfig {
    return PINECONEAuthConfigFromJSONTyped(json, false);
}

export function PINECONEAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PINECONEAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'apiKey': json['api-key'],
    };
}

export function PINECONEAuthConfigToJSON(json: any): PINECONEAuthConfig {
    return PINECONEAuthConfigToJSONTyped(json, false);
}

export function PINECONEAuthConfigToJSONTyped(value?: PINECONEAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'api-key': value['apiKey'],
    };
}

