/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Configuration for Qdrant connector
 * @export
 * @interface QDRANTConfig
 */
export interface QDRANTConfig {
    /**
     * Collection Name. Example: Enter collection name
     * @type {string}
     * @memberof QDRANTConfig
     */
    collection: string;
}

/**
 * Check if a given object implements the QDRANTConfig interface.
 */
export function instanceOfQDRANTConfig(value: object): value is QDRANTConfig {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    return true;
}

export function QDRANTConfigFromJSON(json: any): QDRANTConfig {
    return QDRANTConfigFromJSONTyped(json, false);
}

export function QDRANTConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): QDRANTConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': json['collection'],
    };
}

export function QDRANTConfigToJSON(json: any): QDRANTConfig {
    return QDRANTConfigToJSONTyped(json, false);
}

export function QDRANTConfigToJSONTyped(value?: QDRANTConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': value['collection'],
    };
}

