/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API (Beta)
 * API documentation for Vectorize services
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RetrieveDocumentsRequestContextMessagesInner } from './RetrieveDocumentsRequestContextMessagesInner';
import {
    RetrieveDocumentsRequestContextMessagesInnerFromJSON,
    RetrieveDocumentsRequestContextMessagesInnerFromJSONTyped,
    RetrieveDocumentsRequestContextMessagesInnerToJSON,
    RetrieveDocumentsRequestContextMessagesInnerToJSONTyped,
} from './RetrieveDocumentsRequestContextMessagesInner';

/**
 * 
 * @export
 * @interface RetrieveDocumentsRequestContext
 */
export interface RetrieveDocumentsRequestContext {
    /**
     * 
     * @type {Array<RetrieveDocumentsRequestContextMessagesInner>}
     * @memberof RetrieveDocumentsRequestContext
     */
    messages: Array<RetrieveDocumentsRequestContextMessagesInner>;
}

/**
 * Check if a given object implements the RetrieveDocumentsRequestContext interface.
 */
export function instanceOfRetrieveDocumentsRequestContext(value: object): value is RetrieveDocumentsRequestContext {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function RetrieveDocumentsRequestContextFromJSON(json: any): RetrieveDocumentsRequestContext {
    return RetrieveDocumentsRequestContextFromJSONTyped(json, false);
}

export function RetrieveDocumentsRequestContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrieveDocumentsRequestContext {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': ((json['messages'] as Array<any>).map(RetrieveDocumentsRequestContextMessagesInnerFromJSON)),
    };
}

export function RetrieveDocumentsRequestContextToJSON(json: any): RetrieveDocumentsRequestContext {
    return RetrieveDocumentsRequestContextToJSONTyped(json, false);
}

export function RetrieveDocumentsRequestContextToJSONTyped(value?: RetrieveDocumentsRequestContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': ((value['messages'] as Array<any>).map(RetrieveDocumentsRequestContextMessagesInnerToJSON)),
    };
}

