/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SHAREPOINTConfig } from './SHAREPOINTConfig';
import {
    SHAREPOINTConfigFromJSON,
    SHAREPOINTConfigFromJSONTyped,
    SHAREPOINTConfigToJSON,
    SHAREPOINTConfigToJSONTyped,
} from './SHAREPOINTConfig';

/**
 * 
 * @export
 * @interface Sharepoint
 */
export interface Sharepoint {
    /**
     * Name of the connector
     * @type {string}
     * @memberof Sharepoint
     */
    name: string;
    /**
     * Connector type (must be "SHAREPOINT")
     * @type {string}
     * @memberof Sharepoint
     */
    type: SharepointTypeEnum;
    /**
     * 
     * @type {SHAREPOINTConfig}
     * @memberof Sharepoint
     */
    config: SHAREPOINTConfig;
}


/**
 * @export
 */
export const SharepointTypeEnum = {
    Sharepoint: 'SHAREPOINT'
} as const;
export type SharepointTypeEnum = typeof SharepointTypeEnum[keyof typeof SharepointTypeEnum];


/**
 * Check if a given object implements the Sharepoint interface.
 */
export function instanceOfSharepoint(value: object): value is Sharepoint {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function SharepointFromJSON(json: any): Sharepoint {
    return SharepointFromJSONTyped(json, false);
}

export function SharepointFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sharepoint {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'config': SHAREPOINTConfigFromJSON(json['config']),
    };
}

export function SharepointToJSON(json: any): Sharepoint {
    return SharepointToJSONTyped(json, false);
}

export function SharepointToJSONTyped(value?: Sharepoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'config': SHAREPOINTConfigToJSON(value['config']),
    };
}

