/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SHAREPOINTConfig } from './SHAREPOINTConfig';
import {
    SHAREPOINTConfigFromJSON,
    SHAREPOINTConfigFromJSONTyped,
    SHAREPOINTConfigToJSON,
    SHAREPOINTConfigToJSONTyped,
} from './SHAREPOINTConfig';

/**
 * 
 * @export
 * @interface Sharepoint1
 */
export interface Sharepoint1 {
    /**
     * 
     * @type {SHAREPOINTConfig}
     * @memberof Sharepoint1
     */
    config?: SHAREPOINTConfig;
}

/**
 * Check if a given object implements the Sharepoint1 interface.
 */
export function instanceOfSharepoint1(value: object): value is Sharepoint1 {
    return true;
}

export function Sharepoint1FromJSON(json: any): Sharepoint1 {
    return Sharepoint1FromJSONTyped(json, false);
}

export function Sharepoint1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Sharepoint1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : SHAREPOINTConfigFromJSON(json['config']),
    };
}

export function Sharepoint1ToJSON(json: any): Sharepoint1 {
    return Sharepoint1ToJSONTyped(json, false);
}

export function Sharepoint1ToJSONTyped(value?: Sharepoint1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': SHAREPOINTConfigToJSON(value['config']),
    };
}

