/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SourceConnectorType = {
    AwsS3: 'AWS_S3',
    AzureBlob: 'AZURE_BLOB',
    Confluence: 'CONFLUENCE',
    Discord: 'DISCORD',
    Dropbox: 'DROPBOX',
    DropboxOauth: 'DROPBOX_OAUTH',
    DropboxOauthMulti: 'DROPBOX_OAUTH_MULTI',
    DropboxOauthMultiCustom: 'DROPBOX_OAUTH_MULTI_CUSTOM',
    FileUpload: 'FILE_UPLOAD',
    GoogleDriveOauth: 'GOOGLE_DRIVE_OAUTH',
    GoogleDrive: 'GOOGLE_DRIVE',
    GoogleDriveOauthMulti: 'GOOGLE_DRIVE_OAUTH_MULTI',
    GoogleDriveOauthMultiCustom: 'GOOGLE_DRIVE_OAUTH_MULTI_CUSTOM',
    Firecrawl: 'FIRECRAWL',
    Gcs: 'GCS',
    Zoom: 'ZOOM',
    ZoomAdmin: 'ZOOM_ADMIN',
    Intercom: 'INTERCOM',
    Notion: 'NOTION',
    NotionOauthMulti: 'NOTION_OAUTH_MULTI',
    NotionOauthMultiCustom: 'NOTION_OAUTH_MULTI_CUSTOM',
    OneDrive: 'ONE_DRIVE',
    Sharepoint: 'SHAREPOINT',
    WebCrawler: 'WEB_CRAWLER',
    Github: 'GITHUB',
    Fireflies: 'FIREFLIES',
    Docusign: 'DOCUSIGN',
    Gmail: 'GMAIL'
} as const;
export type SourceConnectorType = typeof SourceConnectorType[keyof typeof SourceConnectorType];


export function instanceOfSourceConnectorType(value: any): boolean {
    for (const key in SourceConnectorType) {
        if (Object.prototype.hasOwnProperty.call(SourceConnectorType, key)) {
            if (SourceConnectorType[key as keyof typeof SourceConnectorType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SourceConnectorTypeFromJSON(json: any): SourceConnectorType {
    return SourceConnectorTypeFromJSONTyped(json, false);
}

export function SourceConnectorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceConnectorType {
    return json as SourceConnectorType;
}

export function SourceConnectorTypeToJSON(value?: SourceConnectorType | null): any {
    return value as any;
}

export function SourceConnectorTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): SourceConnectorType {
    return value as SourceConnectorType;
}

