/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartDeepResearchResponse
 */
export interface StartDeepResearchResponse {
    /**
     * 
     * @type {string}
     * @memberof StartDeepResearchResponse
     */
    researchId: string;
}

/**
 * Check if a given object implements the StartDeepResearchResponse interface.
 */
export function instanceOfStartDeepResearchResponse(value: object): value is StartDeepResearchResponse {
    if (!('researchId' in value) || value['researchId'] === undefined) return false;
    return true;
}

export function StartDeepResearchResponseFromJSON(json: any): StartDeepResearchResponse {
    return StartDeepResearchResponseFromJSONTyped(json, false);
}

export function StartDeepResearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartDeepResearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'researchId': json['researchId'],
    };
}

export function StartDeepResearchResponseToJSON(json: any): StartDeepResearchResponse {
    return StartDeepResearchResponseToJSONTyped(json, false);
}

export function StartDeepResearchResponseToJSONTyped(value?: StartDeepResearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'researchId': value['researchId'],
    };
}

