/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopPipelineResponse
 */
export interface StopPipelineResponse {
    /**
     * 
     * @type {string}
     * @memberof StopPipelineResponse
     */
    message: string;
}

/**
 * Check if a given object implements the StopPipelineResponse interface.
 */
export function instanceOfStopPipelineResponse(value: object): value is StopPipelineResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function StopPipelineResponseFromJSON(json: any): StopPipelineResponse {
    return StopPipelineResponseFromJSONTyped(json, false);
}

export function StopPipelineResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopPipelineResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function StopPipelineResponseToJSON(json: any): StopPipelineResponse {
    return StopPipelineResponseToJSONTyped(json, false);
}

export function StopPipelineResponseToJSONTyped(value?: StopPipelineResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

