/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DestinationConnector } from './DestinationConnector';
import {
    DestinationConnectorFromJSON,
    DestinationConnectorFromJSONTyped,
    DestinationConnectorToJSON,
    DestinationConnectorToJSONTyped,
} from './DestinationConnector';

/**
 * 
 * @export
 * @interface UpdatedDestinationConnectorData
 */
export interface UpdatedDestinationConnectorData {
    /**
     * 
     * @type {DestinationConnector}
     * @memberof UpdatedDestinationConnectorData
     */
    updatedConnector: DestinationConnector;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdatedDestinationConnectorData
     */
    pipelineIds?: Array<string>;
}

/**
 * Check if a given object implements the UpdatedDestinationConnectorData interface.
 */
export function instanceOfUpdatedDestinationConnectorData(value: object): value is UpdatedDestinationConnectorData {
    if (!('updatedConnector' in value) || value['updatedConnector'] === undefined) return false;
    return true;
}

export function UpdatedDestinationConnectorDataFromJSON(json: any): UpdatedDestinationConnectorData {
    return UpdatedDestinationConnectorDataFromJSONTyped(json, false);
}

export function UpdatedDestinationConnectorDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatedDestinationConnectorData {
    if (json == null) {
        return json;
    }
    return {
        
        'updatedConnector': DestinationConnectorFromJSON(json['updatedConnector']),
        'pipelineIds': json['pipelineIds'] == null ? undefined : json['pipelineIds'],
    };
}

export function UpdatedDestinationConnectorDataToJSON(json: any): UpdatedDestinationConnectorData {
    return UpdatedDestinationConnectorDataToJSONTyped(json, false);
}

export function UpdatedDestinationConnectorDataToJSONTyped(value?: UpdatedDestinationConnectorData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'updatedConnector': DestinationConnectorToJSON(value['updatedConnector']),
        'pipelineIds': value['pipelineIds'],
    };
}

