/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Vertex1
 */
export interface Vertex1 {
    /**
     * Configuration updates
     * @type {object}
     * @memberof Vertex1
     */
    config?: object;
}

/**
 * Check if a given object implements the Vertex1 interface.
 */
export function instanceOfVertex1(value: object): value is Vertex1 {
    return true;
}

export function Vertex1FromJSON(json: any): Vertex1 {
    return Vertex1FromJSONTyped(json, false);
}

export function Vertex1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Vertex1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function Vertex1ToJSON(json: any): Vertex1 {
    return Vertex1ToJSONTyped(json, false);
}

export function Vertex1ToJSONTyped(value?: Vertex1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
    };
}

