/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for Voyage AI
 * @export
 * @interface VOYAGEAuthConfig
 */
export interface VOYAGEAuthConfig {
    /**
     * Name. Example: Enter a descriptive name for your Voyage AI integration
     * @type {string}
     * @memberof VOYAGEAuthConfig
     */
    name: string;
    /**
     * API Key. Example: Enter your Voyage AI API Key
     * @type {string}
     * @memberof VOYAGEAuthConfig
     */
    key: string;
}

/**
 * Check if a given object implements the VOYAGEAuthConfig interface.
 */
export function instanceOfVOYAGEAuthConfig(value: object): value is VOYAGEAuthConfig {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function VOYAGEAuthConfigFromJSON(json: any): VOYAGEAuthConfig {
    return VOYAGEAuthConfigFromJSONTyped(json, false);
}

export function VOYAGEAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): VOYAGEAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'key': json['key'],
    };
}

export function VOYAGEAuthConfigToJSON(json: any): VOYAGEAuthConfig {
    return VOYAGEAuthConfigToJSONTyped(json, false);
}

export function VOYAGEAuthConfigToJSONTyped(value?: VOYAGEAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'key': value['key'],
    };
}

