/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WEAVIATEAuthConfig } from './WEAVIATEAuthConfig';
import {
    WEAVIATEAuthConfigFromJSON,
    WEAVIATEAuthConfigFromJSONTyped,
    WEAVIATEAuthConfigToJSON,
    WEAVIATEAuthConfigToJSONTyped,
} from './WEAVIATEAuthConfig';

/**
 * 
 * @export
 * @interface Weaviate1
 */
export interface Weaviate1 {
    /**
     * 
     * @type {WEAVIATEAuthConfig}
     * @memberof Weaviate1
     */
    config?: WEAVIATEAuthConfig;
}

/**
 * Check if a given object implements the Weaviate1 interface.
 */
export function instanceOfWeaviate1(value: object): value is Weaviate1 {
    return true;
}

export function Weaviate1FromJSON(json: any): Weaviate1 {
    return Weaviate1FromJSONTyped(json, false);
}

export function Weaviate1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Weaviate1 {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : WEAVIATEAuthConfigFromJSON(json['config']),
    };
}

export function Weaviate1ToJSON(json: any): Weaviate1 {
    return Weaviate1ToJSONTyped(json, false);
}

export function Weaviate1ToJSONTyped(value?: Weaviate1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': WEAVIATEAuthConfigToJSON(value['config']),
    };
}

