/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Authentication configuration for Web Crawler
 * @export
 * @interface WEBCRAWLERAuthConfig
 */
export interface WEBCRAWLERAuthConfig {
    /**
     * Seed URL(s). Add one or more seed URLs to crawl. The crawler will start from these URLs and follow links to other pages.. Example: (e.g. https://example.com)
     * @type {Array<string>}
     * @memberof WEBCRAWLERAuthConfig
     */
    seedUrls: Array<string>;
}

/**
 * Check if a given object implements the WEBCRAWLERAuthConfig interface.
 */
export function instanceOfWEBCRAWLERAuthConfig(value: object): value is WEBCRAWLERAuthConfig {
    if (!('seedUrls' in value) || value['seedUrls'] === undefined) return false;
    return true;
}

export function WEBCRAWLERAuthConfigFromJSON(json: any): WEBCRAWLERAuthConfig {
    return WEBCRAWLERAuthConfigFromJSONTyped(json, false);
}

export function WEBCRAWLERAuthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WEBCRAWLERAuthConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'seedUrls': json['seed-urls'],
    };
}

export function WEBCRAWLERAuthConfigToJSON(json: any): WEBCRAWLERAuthConfig {
    return WEBCRAWLERAuthConfigToJSONTyped(json, false);
}

export function WEBCRAWLERAuthConfigToJSONTyped(value?: WEBCRAWLERAuthConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seed-urls': value['seedUrls'],
    };
}

