/* tslint:disable */
/* eslint-disable */
/**
 * Vectorize API
 * API for Vectorize services (Beta)
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ZOOMADMINAuthConfig } from './ZOOMADMINAuthConfig';
import {
    ZOOMADMINAuthConfigFromJSON,
    ZOOMADMINAuthConfigFromJSONTyped,
    ZOOMADMINAuthConfigToJSON,
    ZOOMADMINAuthConfigToJSONTyped,
} from './ZOOMADMINAuthConfig';

/**
 * 
 * @export
 * @interface ZoomAdmin
 */
export interface ZoomAdmin {
    /**
     * Name of the connector
     * @type {string}
     * @memberof ZoomAdmin
     */
    name: string;
    /**
     * Connector type (must be "ZOOM_ADMIN")
     * @type {string}
     * @memberof ZoomAdmin
     */
    type: ZoomAdminTypeEnum;
    /**
     * 
     * @type {ZOOMADMINAuthConfig}
     * @memberof ZoomAdmin
     */
    config: ZOOMADMINAuthConfig;
}


/**
 * @export
 */
export const ZoomAdminTypeEnum = {
    ZoomAdmin: 'ZOOM_ADMIN'
} as const;
export type ZoomAdminTypeEnum = typeof ZoomAdminTypeEnum[keyof typeof ZoomAdminTypeEnum];


/**
 * Check if a given object implements the ZoomAdmin interface.
 */
export function instanceOfZoomAdmin(value: object): value is ZoomAdmin {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function ZoomAdminFromJSON(json: any): ZoomAdmin {
    return ZoomAdminFromJSONTyped(json, false);
}

export function ZoomAdminFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZoomAdmin {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'config': ZOOMADMINAuthConfigFromJSON(json['config']),
    };
}

export function ZoomAdminToJSON(json: any): ZoomAdmin {
    return ZoomAdminToJSONTyped(json, false);
}

export function ZoomAdminToJSONTyped(value?: ZoomAdmin | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'config': ZOOMADMINAuthConfigToJSON(value['config']),
    };
}

