# coding: utf-8

"""
    Vectorize API

    API for Vectorize services (Beta)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AIPlatformTypeForPipeline(str, Enum):
    """
    AIPlatformTypeForPipeline
    """

    """
    allowed enum values
    """
    BEDROCK = 'BEDROCK'
    VERTEX = 'VERTEX'
    OPENAI = 'OPENAI'
    VOYAGE = 'VOYAGE'
    VECTORIZE = 'VECTORIZE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AIPlatformTypeForPipeline from a JSON string"""
        return cls(json.loads(json_str))


