# coding: utf-8

"""
    Vectorize API

    API for Vectorize services (Beta)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, SecretStr, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AZUREBLOBAuthConfig(BaseModel):
    """
    Authentication configuration for Azure Blob Storage
    """ # noqa: E501
    storage_account_name: StrictStr = Field(description="Storage Account Name. Example: Enter Storage Account Name", alias="storage-account-name")
    storage_account_key: SecretStr = Field(description="Storage Account Key. Example: Enter Storage Account Key", alias="storage-account-key")
    container: StrictStr = Field(description="Container. Example: Enter Container Name")
    endpoint: Optional[StrictStr] = Field(default=None, description="Endpoint. Example: Enter Endpoint URL")
    __properties: ClassVar[List[str]] = ["storage-account-name", "storage-account-key", "container", "endpoint"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AZUREBLOBAuthConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AZUREBLOBAuthConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "storage-account-name": obj.get("storage-account-name"),
            "storage-account-key": obj.get("storage-account-key"),
            "container": obj.get("container"),
            "endpoint": obj.get("endpoint")
        })
        return _obj


