# coding: utf-8

"""
    Vectorize API

    API for Vectorize services (Beta)

    The version of the OpenAPI document: 0.1.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SINGLESTOREConfig(BaseModel):
    """
    Configuration for SingleStore connector
    """ # noqa: E501
    table: Annotated[str, Field(strict=True, max_length=45)] = Field(description="Table Name. Example: Enter table name")
    __properties: ClassVar[List[str]] = ["table"]

    @field_validator('table')
    def table_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(?!\b(add|alter|all|and|any|as|asc|avg|between|case|check|column|commit|constraint|create|cross|database|default|delete|desc|distinct|drop|else|exists|false|from|full|group|having|in|index|inner|insert|is|join|key|left|like|limit|max|min|not|null|on|or|order|outer|primary|right|rollback|select|set|sum|table|true|union|unique|update|values|view|where)\b$)(?!.*--)(?!.*[-])[a-z][a-z0-9_]{0,44}$", value):
            raise ValueError(r"must validate the regular expression /^(?!\b(add|alter|all|and|any|as|asc|avg|between|case|check|column|commit|constraint|create|cross|database|default|delete|desc|distinct|drop|else|exists|false|from|full|group|having|in|index|inner|insert|is|join|key|left|like|limit|max|min|not|null|on|or|order|outer|primary|right|rollback|select|set|sum|table|true|union|unique|update|values|view|where)\b$)(?!.*--)(?!.*[-])[a-z][a-z0-9_]{0,44}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SINGLESTOREConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SINGLESTOREConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "table": obj.get("table")
        })
        return _obj


