name: CI
on:
  pull_request:
    branches:
      - main

concurrency:
  group: release-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-ts:
    name: Tests (TS)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org/"

      - name: "Install client"
        run: |
          cd src/ts
          npm install
          npm run build
      - name: "Run tests"
        env:
            VECTORIZE_TOKEN: ${{ secrets.VECTORIZE_TOKEN }}
            VECTORIZE_ORG: ${{ secrets.VECTORIZE_ORG }}
            VECTORIZE_ENV: dev
        run: |
          cd src/ts
          npm run test
          
          
